### PR TITLE
Redirect fixed

### LINKED ISSUE #2454: Npm run dev not working correctly in status api folder
**What happened**: When I try to test `/src/api/status` locally by using npm run dev, I received a page that looks messed up

**What should have happened**: It should load css and javascript properly

**How to reproduce it (as precise as possible)**: Go to `/src/api/status`, then `npm install`, then `npm run dev`, and then open up your google chrome and then redirect to `http://localhost:1111/`

**Anything else we need to know?**: It seems like `<base>` at line [19](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/public/index.html#L19) needs to be altered

**Environment**:

- OS: MacOS 12
- Browser: Google Chrome

### PR DESCRIPTION
**Pull request by sirinoks**
## Issue This PR Addresses

    Fixes #2454 

## Type of Change

- [x] **Bugfix**: Now redirects to the required path

## Description

Fixes issue where the root path was displaying wrong. Also fixes one where root is 404
No screenshots, since before the pages didn't work, and now they do.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
I'm confused about this vs https://github.com/Seneca-CDOT/telescope/pull/2493/files, which merged last night cc @drew5494.

**Comment by sirinoks** [comment]
> I'm confused about this vs https://github.com/Seneca-CDOT/telescope/pull/2493/files, which merged last night cc @drew5494.

Yea, I noticed they did a similar thing. It didn't pull their changes for some reason when I was making mine, only showed them when I made a PR. I'm pretty sure it still broke because of the host variable. Shouldn't conflict at this point.

**Comment by humphd** [comment]
If you want to build on that code, please rebase so we isolate your new changes.

**Comment by sirinoks** [comment]
[These lines](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaL34-L35) were replaced by a more compact [single line](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaR37)

[This](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaL38) is basically redundant, since that's what [those lines](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaL34-L35) did

[This](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaR39-R43) fixes a different issue of 404 page on '/'.

[This](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaR4) + [this](https://github.com/Seneca-CDOT/telescope/pull/2494/files#diff-49af73c5ec2f80eafa50b53964f6cbe7aaa34af62b7e41f14d169532eb94d3aaR22) fixes an issue when the build fails if you forgot to put an env. variable in env.local.

File: src/api/status/src/server.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 const { Satellite } = require('@senecacdot/satellite');
 const { static } = require('express');
 const path = require('path');
+const host = process.env.API_HOST || 'localhost';
```
Comment (humphd) [inline src/api/status/src/server.js:4]: Let's do a few things here.  `API_HOST` should be defined.  Let's add it to https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/env.local as `API_HOST=localhost`.

Also, can you fix https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development#L21 to drop the `http://` so that we're consistently using a host vs. origin everywhere.

File: src/api/status/src/server.js [hunk 2]
```diff
@@ -31,11 +32,15 @@ const satelliteOptions = {
 const service = new Satellite(satelliteOptions);
 
 // For local dev, allow specifying a different path prefix (i.e., to mimic Traefik routing with our <base> tag)
-const staticPathPrefix = process.env.PATH_PREFIX || '/';
-service.router.use(staticPathPrefix, static(path.join(__dirname, '../public')));
 
 // Static web assets can be cached for a long time
-service.router.use('/', static(path.join(__dirname, '../public')));
+service.router.use(process.env.PATH_PREFIX || '/', static(path.join(__dirname, '../public')));
```
Comment (humphd) [inline src/api/status/src/server.js:37]: Let's consolidate these various code paths.  We have two cases:

```js
// If a PATH_PREFIX is defined, serve our static content there, and redirect / -> PATH_PREFIX.
// We do this in development to extra path routing that Traefik adds in production (e.g., /v1/status/*)
if (process.env.PATH_PREFIX) {
  service.router.use(process.env.PATH_PREFIX, static(path.join(__dirname, '../public')));
  service.router.get('/', (req, res) => {
    res.redirect(process.env.PATH_PREFIX);
  });
} else {
  service.router.use('/', static(path.join(__dirname, '../public')));
}
```

File: src/api/status/src/server.js [hunk 3]
```diff
@@ -31,11 +32,15 @@ const satelliteOptions = {
 const service = new Satellite(satelliteOptions);
 
 // For local dev, allow specifying a different path prefix (i.e., to mimic Traefik routing with our <base> tag)
-const staticPathPrefix = process.env.PATH_PREFIX || '/';
-service.router.use(staticPathPrefix, static(path.join(__dirname, '../public')));
 
 // Static web assets can be cached for a long time
```
Comment (humphd) [inline src/api/status/src/server.js:36]: This comment can go, it doesn't make sense here.

**Review by humphd — CHANGES_REQUESTED** [review]
OK, your explanation helps me understand.  Thanks for this.

File: src/api/status/src/server.js (hunk 1 above)
Comment (sirinoks) [reply src/api/status/src/server.js:4]: So by adding/changing those two things, we won't need this line anymore?

Comment (humphd) [reply src/api/status/src/server.js:4]: We can do all 3 (leave this line and also change the other 2)

**Comment by sirinoks** [comment]
Code changed based on review

**Review by humphd — APPROVED** [review]
Code looks right, let's get a couple of people to test this locally.

**Review by Andrewnt219 — APPROVED** [review]
Great catch, it feels right to just run `yarn dev` and everything is working. No errors on my local.

One unrelated change I don't know if you can sneak it in this PR. Should we change the default server port to 1112? 1111 is used by `npm run services:start post`.

**Comment by humphd** [comment]
> One unrelated change I don't know if you can sneak it in this PR. Should we change the default server port to 1112? 1111 is used by npm run services:start post.

Why would you want to do this?  Posts uses 5555 https://github.com/Seneca-CDOT/telescope/blob/master/config/env.production#L118.  Can you say more about what you are trying to do?

**Comment by Andrewnt219** [comment]
@humphd Oh wait, my bad, I was running `npx services:start` instead of `npx services:start posts`.
