### PR TITLE
Fixes issue-1355: Display Contributor in Footer of About Page

### LINKED ISSUE #1355: Display Contributor in Footer of About Page
This issue is part of #1232 . As discussed in that issue we would like to add an area to the About page's footer that would highlight Telescopes contributors. 

You will use the `useTelescopeContributor` hook  to fetch a contirbutor that will be displayed in a manner similar to how it is shown on the [node site](https://nodejs.org/en/)

nodeDisplay

### PR DESCRIPTION
**Pull request by Wei-J-Huang**
## Issue This PR Addresses
Fixes #1355 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

I have went ahead and added a new component for the GitHub Contributors using the custom hook from #1330. I was given an example from the Node.js site and took some ideas from it, and made changes to make the Card to better fit into the telescope project visually. I am not sure if we're planning to add more elements to the footer, but in case if we plan to do that in the future, I have decided to have the card positioned on the left for now and leave the center/right empty (unless it's on a small screen device).

View on mobile:
mobile

View on PC:
PC

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
Looks good, was playing around with it and came across this one:
image

image

**Comment by Wei-J-Huang** [comment]
> Looks good, was playing around with it and came across this one:
> image
> 
> image

I took a look and and I believe this might be coming from #1330, in the use-telescope-contributor.js line 4:
```return contributors[Math.floor(Math.random() * contributors.length) + 1];``` 
Perhaps we should remove the +1, seems like it would try to access max length + 1 array element to me which caused the returned object to be undefined.

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+  const classes = useStyles();
+  const theme = useTheme();
+  const { contributor, error } = useTelescopeContributor();
+
+  return { contributor } ? (
+    <Card className={classes.root}>
+      <CardContent>
+        <Grid container direction="row" alignItems="center">
+          <Grid item xs={2}>
+            <Avatar alt="Profile Picture" src={contributor?.avatar_url} />
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:33]: Does every contributor have one avatar?
If so, please use "." instead of "?."

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+              <a
+                href="https://github.com/Seneca-CDOT/telescope/graphs/contributors"
+                className={classes.links}
+              >
+                Telescope project contributor
+              </a>
+              , with your
+              <a
+                href={
+                  'https://github.com/Seneca-CDOT/telescope/commits?author=' + contributor?.login
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:51]: Same here: "." vs "?."

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+          <Grid item xs={2}>
+            <Avatar alt="Profile Picture" src={contributor?.avatar_url} />
+          </Grid>
+          <Grid item xs={10} justify="flex-end">
+            <Typography className={classes.typography}>
+              Thank you{' '}
+              <a href={contributor?.html_url} className={classes.links}>
+                {contributor?.login}
+              </a>
+              , for being a{' '}
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:41]: &nbsp instead of {' '}.

[nbsp example](https://www.w3schools.com/html/html_entities.asp#:~:text=A%20commonly%20used%20entity%20in,the%20words%20might%20be%20disruptive.)

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+      <CardContent>
+        <Grid container direction="row" alignItems="center">
+          <Grid item xs={2}>
+            <Avatar alt="Profile Picture" src={contributor?.avatar_url} />
+          </Grid>
+          <Grid item xs={10} justify="flex-end">
+            <Typography className={classes.typography}>
+              Thank you{' '}
+              <a href={contributor?.html_url} className={classes.links}>
+                {contributor?.login}
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:39]: Same here: "." vs "?."

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+    alignItems: 'flex-start',
+  },
+}));
+
+const GitHubContributorCard = () => {
+  const classes = useStyles();
+  const theme = useTheme();
+  const { contributor, error } = useTelescopeContributor();
+
+  return { contributor } ? (
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:28]: I wonder if you could improve the return to avoid render an "undefined" object.

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+                Telescope project contributor
+              </a>
+              , with your
+              <a
+                href={
+                  'https://github.com/Seneca-CDOT/telescope/commits?author=' + contributor?.login
+                }
+                className={classes.links}
+              >
+                {' '}
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:55]: &nbsp instead of {' '}.

[nbsp example](https://www.w3schools.com/html/html_entities.asp#:~:text=A%20commonly%20used%20entity%20in,the%20words%20might%20be%20disruptive.)

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+                {contributor?.contributions} contribution(s)
```
Comment (PedroFonsecaDEV) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:56]: "?." -> "."

**Review by PedroFonsecaDEV — CHANGES_REQUESTED** [review]

**Comment by PedroFonsecaDEV** [comment]
9259E1DF-56F0-4230-A939-DDC7E97A226B

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx (hunk 1 above)
Comment (PedroFonsecaDEV) [reply src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:33]: Yes, each contributor has one avatar: 
```
{
    "login": "humphd",
    "id": 427398,
    "node_id": "MDQ6VXNlcjQyNzM5OA==",
    "avatar_url": "https://avatars2.githubusercontent.com/u/427398?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/humphd",
    "html_url": "https://github.com/humphd",
    "followers_url": "https://api.github.com/users/humphd/followers",
    "following_url": "https://api.github.com/users/humphd/following{/other_user}",
    "gists_url": "https://api.github.com/users/humphd/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/humphd/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/humphd/subscriptions",
    "organizations_url": "https://api.github.com/users/humphd/orgs",
    "repos_url": "https://api.github.com/users/humphd/repos",
    "events_url": "https://api.github.com/users/humphd/events{/privacy}",
    "received_events_url": "https://api.github.com/users/humphd/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 241
  }```

**Comment by Wei-J-Huang** [comment]
@PedroFonsecaDEV  I've made most of the changes you've mentioned, please give it another review. However, I did not change the position of the card component, since the original issue requested to have it in the footer and I do feel that it visually looks better in the footer, maybe we can leave this as is for now and have a discussion after with others as well?

**Comment by PedroFonsecaDEV** [comment]
> @PedroFonsecaDEV I've made most of the changes you've mentioned, please give it another review. However, I did not change the position of the card component, since the original issue requested to have it in the footer and I do feel that it visually looks better in the footer, maybe we can leave this as is for now and have a discussion after with others as well?

@Wei-J-Huang, I appreciate you getting this to me so quickly. Thanks for getting this done. Sure we can discuss the component's position with others.

**Review by PedroFonsecaDEV — APPROVED** [review]

**Comment by PedroFonsecaDEV** [comment]
Could you please update the title of your PR?
Fixes issue-1355: Display Contributor in Footer of About Page

Thanks.

**Review by PedroFonsecaDEV — DISMISSED** [review]
Please update the title of your PR as requested.

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+import { makeStyles, useTheme } from '@material-ui/core/styles';
+import { Card, CardContent, Typography, Avatar, Grid } from '@material-ui/core';
+import useTelescopeContributor from '../../hooks/use-telescope-contributor';
+
+const useStyles = makeStyles((theme) => ({
+  root: {
+    backgroundColor: theme.palette.primary.light,
+  },
+  typography: {
+    fontSize: 13,
```
Comment (humphd) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:11]: 13 what?  You need a unit on `fontSize`.

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 9]
```diff
@@ -0,0 +1,71 @@
...
+    alignItems: 'flex-start',
+  },
+}));
+
+const GitHubContributorCard = () => {
+  const classes = useStyles();
+  const theme = useTheme();
+  const { contributor, error } = useTelescopeContributor();
+
+  if (contributor !== undefined && contributor !== null) {
```
Comment (humphd) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:28]: This is an anti-pattern.  Instead of deeply indenting the majority of a function's code, you should invert your logic and deal with the negative case first, return, and then continue with the normal case without an indent.  In your case:

```js
if(!contributor) {
  return null;
}

return ( /* rest of your code here */);
```

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+import useTelescopeContributor from '../../hooks/use-telescope-contributor';
+
+const useStyles = makeStyles((theme) => ({
+  root: {
+    backgroundColor: theme.palette.primary.light,
+  },
+  typography: {
+    fontSize: 13,
+  },
+  links: {
```
Comment (humphd) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:13]: `link` singular would make more sense.

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+                </a>
+                , with your
+                <a
+                  href={
+                    'https://github.com/Seneca-CDOT/telescope/commits?author=' + contributor.login
+                  }
+                  className={classes.links}
+                >
+                  &nbsp;
+                  {contributor.contributions} contribution(s)
```
Comment (humphd) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:57]: Let's improve this a bit.  A lot of contributors might have only made 1 contribution, so I think calling out the number is only relevant above some threshold.  I would suggest we do:

```
// 1 or 2 contributions
contributions.

// 3 or more contributions (e.g., 8)
8 contributions.
```

The easiest way to do this might be to split out a tiny component in this same file that looks like:

```jsx
function Contributions({ contributions }) {
  return contributions < 3 ? 'contributions.' : `${contributions} contributions.`;
}

// Now use it like this:
<Contributions contributions={contributor.contributions} />
```

**Review by humphd — CHANGES_REQUESTED** [review]
This is so cool!  A few things to fix and I think it's pretty much ready to go.

**Comment by cindyledev** [comment]
Wow, I love this PR!

**Comment by Wei-J-Huang** [comment]
@humphd Thanks for the suggestions. I've made the changes requested. please give it another review.

**Comment by MLJBrackett** [comment]
This PR looks great 👍

**Review by PedroFonsecaDEV — DISMISSED** [review]
Looks good to me. 
I would think about the contributions' numbers. Maybe it should be more than 5 to display the number. But we can discuss it later.

**Review by MLJBrackett — DISMISSED** [review]

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+    alignItems: 'flex-start',
+  },
+}));
+
+const GitHubContributorCard = () => {
+  const classes = useStyles();
+  const theme = useTheme();
+  const { contributor, error } = useTelescopeContributor();
+
+  if (!contributor) {
```
Comment (humphd) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:28]: We should also deal with the `error` case here.  Probably:

```js
if(error || !contributor) {
  return null;
}
```

File: src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+              </a>
+              , with your
+              <a
+                href={
+                  'https://github.com/Seneca-CDOT/telescope/commits?author=' + contributor.login
+                }
+                className={classes.link}
+              >
+                &nbsp;
+                {contributor.contributions > 2
```
Comment (humphd) [inline src/frontend/src/components/GitHubContributorCard/GitHubContributorCard.jsx:60]: Curious why you didn't do this as a separate functional component to simplify the code here?

**Review by humphd — CHANGES_REQUESTED** [review]

**Review by humphd — APPROVED** [review]

**Comment by Wei-J-Huang** [comment]
@humphd  Thanks for the suggestions again, I should've been more careful with those, they are now updated.

**Review by PedroFonsecaDEV — APPROVED** [review]
