### PR TITLE
SignUp: Update account registration request

### LINKED ISSUE #2886: Sign up flow not working on development
**What happened**:
On development, sign-up flow not working. 
I'm getting a 400 code.

image

**How to reproduce it (as precise as possible)**:

1. git checkout master
2. pnpm i
3. pnpm services:start
4. go to http://localhost:8910/ and http://localhost:8000/
5. On local http://localhost:8000/ do the signup process.

**Environment**:

- OS: Windows 10 Pro edition

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes #2886 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Steps to test the PR
   - `docker-compose build sso nginx && docker-compose up -d`
   -  Go to http://localhost:8000/ to sign up using a test account `user1`:`user1pass`
   - Finish the registration flow and see the new user created in `http://localhost:8910/project/default/editor` -> `telescope_profiles`
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/web/src/pages/signup.tsx [hunk 1]
```diff
@@ -249,59 +253,42 @@ const SignUpPage = () => {
         return <RSSFeeds />;
 
       case SIGN_UP_STEPS.REVIEW:
-        return <Review />;
+        return <Review accountError={telescopeAccount.error} />;
```
Comment (DukeManh) [inline src/web/src/pages/signup.tsx:256]: The current behavior redirects users to an error page if there is a problem creating a new account. It'll be much better if we show this error right in the form so they can edit the information and submit it again.

File: src/api/sso/src/middleware.js [hunk 2]
```diff
@@ -104,16 +104,21 @@ module.exports.createTelescopeUser = function createTelescopeUser() {
...
+      if (status === 409) {
+        next(createError(status, 'Display name or GitHub account has already been registered'));
+      } else {
+        next(createError(status, 'Unable to create a Telescope profile'));
+      }
       return;
     }
 
-    const { error: feedError } = await supabase.from('feeds').insert(
+    response = await supabase.from('feeds').insert(
```
Comment (humphd) [inline src/api/sso/src/middleware.js:121]: Instead of re-using `response` here, I wonder if you should break these two sections into separate functions that you call together.

File: src/web/src/components/SignUp/Schema/FormSchema.tsx [hunk 3]
```diff
@@ -21,14 +21,14 @@ export default [
...
+    [lastName.name]: Yup.string().required(lastName.requiredErrorMsg),
+    [displayName.name]: Yup.string().required(displayName.requiredErrorMsg),
   }),
 
   // Second step we fetch data from GitHub.
   Yup.object().shape({
-    [githubUsername.name]: Yup.string().required(`${githubUsername.requiredErrorMsg}`),
+    [githubUsername.name]: Yup.string().required(githubUsername.requiredErrorMsg),
     [github.name]: Yup.object()
       .shape({
```
Comment (humphd) [inline src/web/src/components/SignUp/Schema/FormSchema.tsx:33]: So you're thinking to keep it as an Object, but just send it in the correct format to/from the server vs. splitting these apart here as well?

**Review by humphd — CHANGES_REQUESTED** [review]
Looks good, a couple small things.

File: src/web/src/components/SignUp/Schema/FormSchema.tsx (hunk 3 above)
Comment (DukeManh) [reply src/web/src/components/SignUp/Schema/FormSchema.tsx:33]: Right, because there are 2 GitHub usernames, one is the user input, one is the one we get from GitHub, for displaying under the avatar. If we use just one, then the name under the avatar will change on input change and it doesn't match the avatar until we click `Get GitHub Profile`.

File: src/api/sso/src/middleware.js (hunk 2 above)
Comment (DukeManh) [reply src/api/sso/src/middleware.js:121]: Ok, let me try that, the test is failing btw.

File: src/api/sso/src/routes/logout.js [hunk 4]
```diff
@@ -24,7 +24,7 @@ function logout() {
     }
 
     const { redirectUri, state } = req.session.authDetails;
-    delete req.session.authDetails;
+    req.session.destroy();
```
[the remark this answers is not in the document]
Comment (humphd) [reply src/api/sso/src/routes/logout.js:27]: Can we separate this change from what you're doing here?  Logout logic is tricky to get right with SSO.  File a follow-up.

[the remark this answers is not in the document]
Comment (DukeManh) [reply src/api/sso/src/routes/logout.js]: Gotcha

File: src/api/sso/src/middleware.js [hunk 5]
```diff
@@ -85,35 +85,32 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
-
-    if (userError) {
-      logger.warn(
-        { code: userError.code, details: userError.details, id, data: req.body },
-        userError.message
-      );
-      next(createError(400, 'unable to create user'));
-      return;
-    }
+const isFeedExists = async (feeds) => {
```
Comment (humphd) [inline src/api/sso/src/middleware.js:88]: `feedExists` or `checkFeedExists` (grammar is wrong with `is` here)

**Review by humphd — COMMENTED** [review]
On nit, code looks great.

**Review by joelazwar — DISMISSED** [review]
looks great! tested locally 👍 
image

File: src/api/sso/src/middleware.js [hunk 6]
```diff
@@ -122,18 +119,34 @@ module.exports.createTelescopeUser = function createTelescopeUser() {
...
-    if (feedError) {
-      logger.warn(
-        { code: feedError.code, details: feedError.details, id, data: req.body },
-        feedError.message
-      );
-      // Delete the newly created user if their feeds are invalid
-      await supabase.from('telescope_profiles').delete({ returning: 'minimal' }).match({ id });
-      next(createError(400, 'User feed is invalid or already exists'));
+    if (await checkFeedExists(req.body.feeds)) {
+      next(createError(409, 'A Feed URL has already been registered'));
```
Comment (humphd) [inline src/api/sso/src/middleware.js:131]: Can you file a follow-up issue to add a test for this case?  I don't think we have this in the sso e2e tests, and we should.

**Review by humphd — APPROVED** [review]
Fantastic.  One request for a follow-up issue, and this is good to go!

**Comment by TueeNguyen** [comment]
I wasn't able to run this `docker-compose build sso nginx && docker-compose up -d`

**Comment by humphd** [comment]
You really need to run it via `pnpm services:start` so it uses the right set of docker-compose files.  Also, I ran into issues with the nginx build last week, and had to remove the old image/containers and start again.  I'm not sure what landed that broke things, but I couldn't solve without pruning.

File: src/api/sso/src/middleware.js (hunk 6 above)
Comment (DukeManh) [reply src/api/sso/src/middleware.js:131]: https://github.com/Seneca-CDOT/telescope/issues/2909

**Comment by DukeManh** [comment]
@TueeNguyen Let me know when you test or you need help to test it before I merge.

**Comment by TueeNguyen** [comment]
Sorry for testing late, so I ran using `pnpm services:start` and do I click `Sign In` next to sign up? @DukeManh

**Comment by DukeManh** [comment]
My branch would should `Unable to post user info` vs `Unable to Post`, so I think you might be on the wrong branch or have not built the new image.

**Comment by TueeNguyen** [comment]
Hehe sorry Duke, it works :) 
image

**Review by TueeNguyen — APPROVED** [review]

**Comment by joelazwar** [comment]
> Hehe sorry Duke, I checked out to a different branch, it works :) image

I was guilty of this too ! 🤣

**Review by joelazwar — APPROVED** [review]
