### PR TITLE
Fixed Issue #2627: Changed naming of Users to Users/Org

### LINKED ISSUE #2627: Fix naming of "Users" in GitHub Info
What we're calling "Users" in the GitHub info sidebar is really "Users/Orgs" or "Users and Orgs":

Screen Shot 2021-12-18 at 9 47 56 AM

### PR DESCRIPTION
**Pull request by HyperTHD**
## Issue This PR Addresses
This PR resolves #2627 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Just a simple naming change to how we represent multiple users/orgs when mentioned in a blog post. Delayed mainly due to taking it during the holidays and covid :( (Doing amazing right now though)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by tpmai22 — APPROVED** [review]

File: src/web/src/components/Posts/Users.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ const Users = ({ usernames, avatarSize = 25 }: Props) => {
     <div className={classes.GitHubInfo}>
       <h2 className={classes.GitHubLinkTitle}>
         <VscGithub className={classes.icon} />
-        {usernames.length === 1 ? 'User' : 'Users'}
+        {usernames.length === 1 ? 'User' : 'Users/Orgs'}
```
Comment (AmasiaNalbandian) [inline src/web/src/components/Posts/Users.tsx:54]: Can we do User/Org as well? Singular doesn't guarantee it's just a user does it?

**Review by AmasiaNalbandian — CHANGES_REQUESTED** [review]

File: src/web/src/components/Posts/Users.tsx (hunk 1 above)
Comment (HyperTHD) [reply src/web/src/components/Posts/Users.tsx:54]: I don't remember exactly but I can add that in too

**Review by humphd — APPROVED** [review]

**Review by DukeManh — APPROVED** [review]

**Review by tpmai22 — APPROVED** [review]

**Review by AmasiaNalbandian — APPROVED** [review]
