### PR TITLE
Fix #2449: add border for telescope avatar

### LINKED ISSUE #2449: Add border to avatar
I notice that GitHub uses a slight border around the avatars, and we don't:

Screen Shot 2021-11-04 at 9 58 50 AM

Let's steal this.  They look wrong without it.

### PR DESCRIPTION
**Pull request by tuanthanh2067**
## Issue This PR Addresses
This PR closes #2449 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [X] **UI**: Change which improves UI

## Description

I added a border for telescope avatar, and the color does not stand out. 

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2450"></a>

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
Because we're using GitHub avatars, let's use their styling so it looks "right":

Screen Shot 2021-11-04 at 3 44 57 PM

Can you dig around in the GitHub CSS with your dev tools and get the colours they use and do it the same way?

**Comment by tuanthanh2067** [comment]
It seems like github uses different border colors for their different themes.

**Comment by HyperTHD** [comment]
Just for future PRs, please indicate what issue you close in the PR itself as well as the title, so the issue will automatically get linked to the PR and close both whenever your PR gets merged

**Comment by tuanthanh2067** [comment]
Noted, sorry for the title.

File: src/web/src/components/TelescopeAvatar.tsx [hunk 1]
```diff
@@ -8,6 +17,7 @@ type TelescopeAvatarProps = {
   url?: string;
   backgroundColor?: string;
   fontColor?: string;
+  borderColor?: string;
```
Comment (DukeManh) [inline src/web/src/components/TelescopeAvatar.tsx:20]: I wonder if we need `borderColor` prop if we're not using it anywhere?

File: src/web/src/components/TelescopeAvatar.tsx [hunk 2]
```diff
@@ -1,5 +1,14 @@
 import { MouseEventHandler } from 'react';
 import { Avatar } from '@material-ui/core';
+import { createStyles, makeStyles, Theme } from '@material-ui/core';
+
+const useStyles = makeStyles((theme: Theme) =>
+  createStyles({
+    image: {
+      border: `1px solid ${theme.palette.border.main}`,
```
Comment (DukeManh) [inline src/web/src/components/TelescopeAvatar.tsx:8]: I notice GitHub uses `0 0 0 1px rgba(27,31,36,0.15)` for light mode and `0 0 0 1px rgba(240,246,252,0.1)` for dark mode.
Since we're using their avatar let's copy them as is.

**Review by DukeManh — CHANGES_REQUESTED** [review]

File: src/web/src/components/TelescopeAvatar.tsx (hunk 2 above)
Comment (tuanthanh2067) [reply src/web/src/components/TelescopeAvatar.tsx:8]: Actually i converted rgba(...) to hex code

**Review by humphd — CHANGES_REQUESTED** [review]
I'm confused, why not just do what GitHub is doing?  Why is this blue vs. gray?

Compare:

Screen Shot 2021-11-09 at 7 54 26 PM

**Comment by tuanthanh2067** [comment]
Oh Github uses box-shadow instead of border.

**Review by DukeManh — APPROVED** [review]

**Review by humphd — DISMISSED** [review]
Please squash and rebase this, and then we can merge

**Review by DukeManh — APPROVED** [review]
