### PR TITLE
Fixes #1166: /graphql playground broken due to CORS issue

### LINKED ISSUE #1166: /graphql playground broken due to CORS issue
https://dev.telescope.cdot.systems/qraphql should be our graphql playground link, but it is currently broken with what looks like a CORS and/or CSP violation:

```
Refused to load the image 'https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.33/build/favicon.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".

graphql:1 Refused to load the script 'https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.33/build/static/js/middleware.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

graphql:531 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-PT+YOJyhu3IamY7Pf1cnvQbDxlHIK2FjqtA7GQoyN5U='), or a nonce ('nonce-...') is required to enable inline execution.

graphql:1 Refused to load the image 'https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.33/build/favicon.png' because it violates the following Content Security Policy directive: "img-src 'self' data:".
```

### PR DESCRIPTION
**Pull request by manekenpix**
## Issue This PR Addresses
Fixes #1166 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This changes our settings for development to allow `graphql`'s playground to load the necessary scripts for its playground

**Note** (from [Apollo's documentation](https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/)):
> In development, Apollo Server enables GraphQL Playground on the same URL as the GraphQL server itself (e.g. http://localhost:4000/graphql) and automatically serves the GUI to web browsers. When NODE_ENV is set to production, GraphQL Playground (as well as introspection) is disabled as a production best-practice.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/web/app.js [hunk 1]
```diff
@@ -18,8 +18,33 @@ const router = require('./routes');
...
+app.use(
+  helmet({
+    contentSecurityPolicy:
+      process.env.NODE_ENV === 'development'
+        ? {
+            directives: {
+              defaultSrc: ["'self'"],
+              baseUrl: ["'self'"],
+              fontSrc: ["'self'", 'https:', 'data:'],
+              frameAncestors: ["'self'"],
```
Comment (humphd) [inline src/backend/web/app.js:37]: Will this break YouTube and Vimeo embeds?

Comment (manekenpix) [reply src/backend/web/app.js:36]: Yes, thanks for pointing that out. I added (and tested) `frameSrc` to allow content from `youtube` and `vimeo`.

File: src/backend/web/app.js [hunk 2]
```diff
@@ -18,8 +18,32 @@ const router = require('./routes');
...
+      process.env.NODE_ENV === 'development'
+        ? {
+            directives: {
+              defaultSrc: ["'self'"],
+              fontSrc: ["'self'", 'https:', 'data:'],
+              frameSrc: ["'self'", '*.youtube.com', '*.vimeo.com'],
+              frameAncestors: ["'self'"],
+              imgSrc: ["'self'", 'data:', 'https:'],
+              scriptSrc: ["'self'", 'cdn.jsdelivr.net', "'unsafe-inline'"],
+              styleSrc: ["'self'", 'https:', "'unsafe-inline'"],
```
Comment (humphd) [inline src/backend/web/app.js:39]: We might be able to leave this at `'self'`, but we can roll this back later.

**Review by humphd — APPROVED** [review]

**Review by c3ho — APPROVED** [review]
