### PR TITLE
ReOpen: Fix#Issue 1311 - validate GET /posts/:id route using Express Validator

### LINKED ISSUE #1311: Add query params validation for GET /posts/:id route using Express Validator and unit tests
**What would you like to be added**: 
Request to add query params validation for GET /posts/:id route using [Express-validator](https://express-validator.github.io/docs/) and also unit tests to ensure that it works

**Why would you like this to be added**:
It would be better to validate the query before it reach the route handler. 

reference: https://express-validator.github.io/docs/check-api.html

All logic for the middleware should be place inside `backend/web/validation.js`

### PR DESCRIPTION
**Pull request by eunbeek**
## Issue This PR Addresses

Fixes #1311 
https://github.com/Seneca-CDOT/telescope/issues/1311

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
 

The validation will check the length of the parameter 'Id' in posts. In this issue, I only applied it to GET /posts/:id but it could be applied to any posts url with id param.  Normal id length is 10 and the reason why I used the length check is the id value is encoded by hash algorithms and sliced to 10 characters. 

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by tonyvugithub** [comment]
@eunbeek : hey, great work from you so far. We are currently ensuring we have a consistent layout for all validations. So bear with us for a bit longer. Your codes are good but we will request you to make one more change after we merge the commit from @zg3d . You can take a look at his commit here. 
https://github.com/Seneca-CDOT/telescope/pull/1361/commits/b9a87872b1775f8e8fc0cb3bee468023b0aa656a
After we merge his. You can simply adjust your code a bit then commit again. Should not take you a long time.

**Comment by tonyvugithub** [comment]
@eunbeek : great news, the other commit got merged. Please follow the style in this commit https://github.com/Seneca-CDOT/telescope/pull/1361/commits/1a2f541c28399c163b8d560189c2f66d2f481313 and revise your code accordingly and push again. Remember to rebase before pushing

**Review by tonyvugithub — CHANGES_REQUESTED** [review]
check comments!

File: src/backend/web/validation.js [hunk 1]
```diff
@@ -89,7 +89,27 @@ const validateQuery = () => {
...
+    await Promise.all(validatePostsIdParamRules().map((rule) => rule.run(req)));
+
+    const errors = validationResult(req);
+    if (errors.isEmpty()) {
+      return next();
+    }
+    return res.status(400).json({ errors: errors.array() });
+  };
+};
+
```
Comment (tonyvugithub) [inline src/backend/web/validation.js]: There is a common function in the current stage of validation.js 
`// creates a validation middleware with any given rules
const validate = (rules) => {
  return async (req, res, next) => {
    await Promise.all(rules.map((rule) => rule.run(req)));

    const result = validationResult(req);
    if (result.isEmpty()) {
      return next();
    }

    const errors = result.array();
    return res.status(400).send(errors);
  };
};`
So this function should be narrow to something similar to as we try to have dry code 
`module.exports = {
  validateNewFeed,	  
  validateQuery: () => validate(queryValidationRules),
  validatePostsQuery: () => validate(postsQueryValidationRules),
};`
Best way to do this is to have your code save somewhere, rebase your master start adding your code according to the current state of validation.js. You can also check this commit https://github.com/Seneca-CDOT/telescope/pull/1361/commits/1a2f541c28399c163b8d560189c2f66d2f481313

**Review by tonyvugithub — CHANGES_REQUESTED** [review]

File: src/backend/web/validation.js (hunk 1 above)
Comment (eunbeek) [reply src/backend/web/validation.js]: @tonyvugithub I have a hard time to resolve commit conflict......I fixed it you mentioned but my commit is twist. I will update it to my master and wil pull request soon

Comment (eunbeek) [reply src/backend/web/validation.js:104]: @tonyvugithub Finally I made 5 commit to single commit. Thanks!
@zg3d  I did my part by following your style.

so, Could you check my work?

**Review by zg3d — APPROVED** [review]
Alright, great work looks  good to me.

**Review by tonyvugithub — APPROVED** [review]
