### PR TITLE
Fixes #1169: Fix search posts

### LINKED ISSUE #1169: 'Search' returns latest posts instead of results for searched input.
**What happened**:
I entered a string in the search box and it returned the latest posts instead of actual results

Peek 2020-10-08 11-58

**What should have happened**:
I should have seen posts related to the entered string

**How to reproduce it (as precise as possible)**:
Go to https://dev.telescope.cdot.systems/search, enter any string in the search box and compare results to latest posts in `/`

### PR DESCRIPTION
**Pull request by c3ho**
## Issue This PR Addresses
Fixes #1169 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
This PR allows users to search posts again.

I tried to change as little code as possible for this PR, such as assigning the passed results from search as props and then assigning it to `posts`. `Load More Posts` button will not show anymore if we're searching posts.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/src/components/Posts/Posts.jsx [hunk 1]
```diff
@@ -78,8 +79,14 @@ const Posts = () => {
         setLoading(false);
       }
     }
+    if (searchPostResults) {
+      setPosts(searchPostResults);
+      console.log('hi');
```
Comment (humphd) [inline src/frontend/src/components/Posts/Posts.jsx:84]: Hi

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/frontend/src/components/Posts/Posts.jsx [hunk 2]
```diff
@@ -78,8 +79,14 @@ const Posts = () => {
...
+    } else {
+      getPosts();
+      console.log('bye');
```
Comment (raygervais) [inline src/frontend/src/components/Posts/Posts.jsx:87]: Bye

**Review by raygervais — CHANGES_REQUESTED** [review]

File: src/frontend/src/components/Posts/Posts.jsx [hunk 3]
```diff
@@ -46,6 +46,7 @@ const Posts = () => {
   const [posts, setPosts] = useState([]);
   const [numPages, setNumPages] = useState(1);
   const [endOfPosts, setEndOfPosts] = useState(false);
+  const { searchPostResults } = props;
```
Comment (humphd) [inline src/frontend/src/components/Posts/Posts.jsx:49]: So it makes more sense to pass in the search results here vs. doing it in this component?

I would have thought doing:

```jsx
<Posts search="This is my search text" author="Calvin Ho" />
```

would have been more logical.  But maybe the code doesn't allow this easily?

Comment (c3ho) [reply src/frontend/src/components/Posts/Posts.jsx:49]: We have two separate components, depending on what type of search is being carried out: if by posts, we reuse the post component and just pass it everything,

If they search by author: we have an author results component that is displayed instead with no posts, so I'm not sure we'll need to pass the author information

Comment (humphd) [reply src/frontend/src/components/Posts/Posts.jsx:49]: OK, we can evolve this in follow up PRs then.  Let's keep this one focused on getting results into Posts.

File: src/frontend/src/components/Posts/Posts.jsx [hunk 4]
```diff
@@ -212,7 +220,8 @@ const Posts = () => {
 
 Posts.propTypes = {
   className: PropTypes.string,
-  posts: PropTypes.array,
+  searchResults: PropTypes.array,
+  searchPostResults: PropTypes.array,
```
Comment (humphd) [inline src/frontend/src/components/Posts/Posts.jsx:224]: Why do we have two props here?  You only appear to use `searchResults` in the component.  Let's remove `searchPostResults`

Comment (humphd) [reply src/frontend/src/components/Posts/Posts.jsx:224]: Another question re: naming - if what we're passing into this component on props are actually `posts` then maybe that's the right name vs. `searchResults` (i.e.,. it's more accurate, generic, and reusable for the `Posts` component)?

```jsx
<!-- No posts are being passed, load them internally -->
<Posts />

<!-- We are passing posts to be rendered -->
<Posts posts={...} />
```

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/frontend/src/components/Posts/Posts.jsx (hunk 4 above)
Comment (c3ho) [reply src/frontend/src/components/Posts/Posts.jsx:224]: I wanted to use `posts`, however we are using that variable already in [posts](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Posts/Posts.jsx#L46) to declare an empty array and append to as we get more posts. React also yells at me to use object destructuring, unless you want me to ignore it and use something like `const (variable) = props.posts`

Comment (humphd) [reply src/frontend/src/components/Posts/Posts.jsx:224]: Gotcha.  Let's call it `searchResults` then, and you can use destructing if you want, sure.  Remove the second prop in proptypes.

**Review by humphd — DISMISSED** [review]

**Review by cindyledev — DISMISSED** [review]

**Comment by c3ho** [comment]
Merging as this previously received 2 approvals prior to rebase.
