### PR TITLE
Fixes #591, Add filters to GraphQL

### LINKED ISSUE #591: Add filters to GraphQL to remove getPost
**What happened**:

Recently #565 was merged and the way we store posts and feeds changed. That affected GraphQL, specifically our [getPost](https://github.com/Seneca-CDOT/telescope/blob/08c55d4d694cf7b8a2c37b7945606c792976191d/src/backend/web/graphql/index.js#L40) query. `getPost` was kept for legacy reasons, so this issue wont' prevent Telescope from serving all available posts.
Instead of patching `getPost`, it'd be better if we implement filters that would work with our getPosts query, that way we could filter by any subfield included in our Post type.

**How to reproduce it (as precise as possible)**:

Use the getPost query passing a `guid` as argument.

### PR DESCRIPTION
**Pull request by c3ho**
## Issue This PR Addresses
Fixes #591 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Rough work for now. You can test this by doing the following: 

image

filters are optional, to change another one simply change the last line,
to use two such as fromDate and toDate

```
{
  getPosts(page: 10, perPage: 10, filter: {fromDate: "Enter fromDate here", toDate: "Enter ToDate here"}){
    author
  }
}
```

Pretty sure the above one doesn't work yet as I'm messing up over the date/time things

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/web/graphql/index.js [hunk 1]
```diff
@@ -36,9 +36,31 @@ module.exports.typeDefs = graphql`
...
+    ne: String
+    in: String
+    nin: String
+    regex: String
+  }
+
+  input IntFilter {
+    eq: Int
+    ne: Int
+  }
```
Comment (c3ho) [inline src/backend/web/graphql/index.js]: probably don't need these

File: src/backend/web/graphql/index.js [hunk 2]
```diff
@@ -94,7 +116,24 @@ module.exports.resolvers = {
...
+          // check if author name is equal to what we're searching for.
+          if (filter.author) {
+            return result.filter(posts => posts.author === filter.author);
+          }
+          // check if published date is between
+          if (filter.fromDate && filter.toDate) {
+            const fromDate = new Date(filter.fromDate);
+            const toDate = new Date(filter.toDate);
+            return result.filter(
+              posts => parseInt(posts.published, 10) >= fromDate && posts.published <= toDate
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: Filter usually defines a plural form, and the callback a singuluar:

```js
posts.filter(post => ...)
```

Also, a `post` uses `Date` for `published` and `updated` (it's only a number of MS in Redis, but we convert it when you call `Post.byId`).  Also, in my PR for #631, I'm adding a way to query Redis for posts only within a date range.  It might make this easier, so you don't have to request them all, and filter.  You'd only have to filter for other fields within that bounded set of posts that meet the date range specified.

**Comment by c3ho** [comment]
can iterate on this, with the other libraries and stuff. Just want to get the filters kind of working so I can give a demo

File: src/backend/web/graphql/index.js [hunk 3]
```diff
@@ -36,9 +36,38 @@ module.exports.typeDefs = graphql`
...
-    getPosts(page: Int, perPage: Int): [Post]
+    getPosts(filter: PostFilter, page: Int, perPage: Int): [Post]
     getPostsCount: Int
   }
+
+  # Post filters
+  input PostFilter {
+    author: String
+    fromDate: Int
+    toDate: Int
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: Why use `Int` for these dates?  Won't most callers of this expect to be able to use Date objects?

File: src/backend/web/graphql/index.js (hunk 1 above)
Comment (humphd) [reply src/backend/web/graphql/index.js]: Should you remove them then?

File: src/backend/web/graphql/index.js [hunk 4]
```diff
@@ -94,7 +123,26 @@ module.exports.resolvers = {
...
+        if (filter) {
+          // check if author name is equal to what we're searching for
+          if (filter.author) {
+            return result.filter(post => post.author === filter.author);
+          }
+          // check if published date is between two provided dates
+          if (filter.fromDate || filter.toDate) {
+            const fromDate = filter.fromDate ? new Date(filter.fromDate * 1000) : new Date();
+            const toDate = filter.toDate ? new Date(filter.toDate * 1000) : new Date();
+            return result.filter(post => post.published >= fromDate && post.published <= toDate);
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: So you're not using the stuff I landed for stats yet.  Are you going to move toward that?

File: src/backend/web/graphql/index.js [hunk 5]
```diff
@@ -94,7 +122,27 @@ module.exports.resolvers = {
...
+            const datePostIds = await getPostsByDate(fromDate, toDate);
+            return result.filter(post => datePostIds.includes(post.id));
+          }
+          // check if url is equal to what we're searching for
+          if (filter.url) {
+            return result.filter(post => post.url === filter.url);
+          }
+        }
+
+        return result;
```
Comment (c3ho) [inline src/backend/web/graphql/index.js]: I don't know why the results are being the way they are. 

It might also be I'm not entirely sure of how the flow should be at the moment.
How I'm thinking it should work

1. We get the page results, so say we're getting the first 30 results of page 1.
2. We filter those 30 results by the date filter now

or should we ...
1. Get the results with the filter
2. Apply pagination on the filtered results

Playing around with the filter, I have no idea why the results are so different:
for example with 
```
{
  getPosts(page: 1, perPage: 10, filter: {fromDate: "2020-01-01"}){
    author
    published
    title
  }
}
```
image

but if I change perPage to say 20
```
{
  getPosts(page: 1, perPage: 20, filter: {fromDate: "2020-01-01"}){
    author
    published
    title
  }
}
```
image

The results seem like they're going backwards..?

**Comment by c3ho** [comment]
I think something else to think about, do we want to do a == match or something like string contains `string.match(regExp)`  based on user input?

File: src/backend/web/graphql/index.js [hunk 6]
```diff
@@ -94,7 +122,27 @@ module.exports.resolvers = {
...
+        if (filter) {
+          // check if author name is equal to what we're searching for
+          if (filter.author) {
+            return result.filter(post => post.author === filter.author);
+          }
+          // check if post's date is between two provided dates
+          if (filter.fromDate || filter.toDate) {
+            const fromDate = filter.fromDate ? filter.fromDate : new Date();
+            const toDate = filter.toDate ? filter.toDate : new Date();
+            const datePostIds = await getPostsByDate(fromDate, toDate);
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: I think you need to check if you're doing a date-filter earlier, since there is no point getting all posts on line 123 if you are going to do it again here by date.  Move your filter checks up, and decide which way to get posts based on that.

File: src/backend/web/graphql/index.js [hunk 7]
```diff
@@ -94,7 +122,27 @@ module.exports.resolvers = {
...
+            return result.filter(post => datePostIds.includes(post.id));
+          }
+          // check if url is equal to what we're searching for
+          if (filter.url) {
+            return result.filter(post => post.url === filter.url);
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: We should call the code in `normalize-url` here, so the URLs match more closely.  See https://github.com/Seneca-CDOT/telescope/blob/11700c087602f83838a9a9a67ffe403f8db2cce1/src/backend/data/feed.js#L1

File: src/backend/web/graphql/index.js (hunk 5 above)
Comment (humphd) [reply src/backend/web/graphql/index.js]: I might be that you get counts based on not filtering, but then sometimes filter (by date).  The posts and count should only get processed once you know about the filters you are using.

File: src/backend/web/graphql/index.js (hunk 6 above)
Comment (c3ho) [reply src/backend/web/graphql/index.js]: I think this was the question I wanted to ask, are we going to do the pagination first. As in

1. I want to see 30 posts on page 0
2. Out of those 30 posts I want to see the ones that are from "February 2, 2020" to "February 07, 2020". I'll then compare which of those posts on page 0 are within the results from `getPostsByDate()`

Comment (humphd) [reply src/backend/web/graphql/index.js]: Pagination only makes sense in the context of your data, so calculate the posts you have first, then figure out pages after that

File: src/backend/web/graphql/index.js [hunk 8]
```diff
@@ -113,37 +113,56 @@ module.exports.resolvers = {
      * @return Array of 'perPage' number of Post objects
      */
     getPosts: async (parent, { filter, page, perPage }) => {
+      let postIds;
+      const numOfPosts = await getPostsCount();
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: Do this later: depending on how we filter, it will be different (all posts vs. date range)

File: src/backend/web/graphql/index.js [hunk 9]
```diff
@@ -113,37 +113,56 @@ module.exports.resolvers = {
...
 
-      const numOFPosts = await getPostsCount();
-      const first = page * prPage;
-
-      if (first < numOFPosts) {
-        const last = first + prPage < numOFPosts ? first + prPage : numOFPosts;
-        const postIds = await getPosts(first, last);
-
+      // For Date Filter
+      if (filter) {
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: Flip this logic: `if (!filter) {...}` since the code for the other case is smaller, and then you can `return` and not indent all this.

Even better, split this out into a separate function.

File: src/backend/web/graphql/index.js [hunk 10]
```diff
@@ -113,37 +113,56 @@ module.exports.resolvers = {
...
+        if (filter.fromDate || filter.toDate) {
+          const fromDate = filter.fromDate ? filter.fromDate : new Date();
+          const toDate = filter.toDate ? filter.toDate : new Date();
+          postIds = await getPostsByDate(fromDate, toDate); // Get all results within the date
+          // check if # of filtered results are less than max results allowed per page.
+          if (postIds.length < prPage) {
+            return Promise.all(postIds.map(id => Post.byId(id))); // return all the posts' info
```
Comment (humphd) [inline src/backend/web/graphql/index.js]:
```js
return Promise.all(postIds.map(Post.byId));
```

File: src/backend/web/graphql/index.js [hunk 11]
```diff
@@ -113,37 +113,56 @@ module.exports.resolvers = {
...
+          }
+          // Otherwise do some pagination here
+          const pageResult = postIds.slice(page - 1 * perPage, page * prPage);
+          return Promise.all(pageResult.map(id => Post.byId(id)));
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: Same thing here, shorten to `(Post.byId)`

File: src/backend/web/graphql/index.js [hunk 12]
```diff
@@ -113,37 +113,56 @@ module.exports.resolvers = {
...
+      }
 
-        return result;
+      const first = page * prPage;
+
+      if (first < numOfPosts) {
+        const last = first + prPage < numOfPosts ? first + prPage : numOfPosts;
+        postIds = await getPosts(first, last);
+
+        return Promise.all(postIds.map(id => Post.byId(id)));
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: `map(Post.byId)`

File: src/backend/web/graphql/index.js [hunk 13]
```diff
@@ -84,18 +112,57 @@ module.exports.resolvers = {
...
+          const authorResults = result.filter(post => post.author === filter.author);
+          // check if # of filtered results are less than max results allowed per page.
+          if (authorResults.length < prPage) {
+            return authorResults;
+          }
+          return authorResults.slice(page - 1 * perPage, page * prPage);
+        }
+
+        if (filter.author) {
+          const urlResults = result.filter(post => post.url === normalize(filter.url));
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: You should normalize both of these URLs before you compare:

```js
const urlResults = result.filter(post => normalize(post.url) === normalize(filter.url));
```

File: src/backend/web/graphql/index.js [hunk 14]
```diff
@@ -84,18 +112,57 @@ module.exports.resolvers = {
...
+          if (postIds.length < prPage) {
+            return Promise.all(postIds.map(id => Post.byId(id))); // return all the posts' info
+          }
+          // Otherwise do some pagination here
+          const pageResult = postIds.slice(page - 1 * perPage, page * prPage);
+          return Promise.all(pageResult.map(id => Post.byId(id)));
+        }
+        // Other filters use the getPosts() instead of getPostsByDate()
+        postIds = await getPosts(0, numOfPosts);
+        const result = await Promise.all(postIds.map(id => Post.byId(id)));
```
Comment (humphd) [inline src/backend/web/graphql/index.js]: `posts` vs. `result`?

File: src/backend/web/graphql/index.js [hunk 15]
```diff
@@ -84,18 +112,57 @@ module.exports.resolvers = {
...
+
+        if (filter.url) {
```
Comment (manekenpix) [inline src/backend/web/graphql/index.js]: I think you have `if(filter.url)` here (but this deals with authors, and `if(filter.author)` below this where you deal with urls.

File: src/backend/web/graphql/index.js (hunk 10 above)
Comment (c3ho) [reply src/backend/web/graphql/index.js]: You can do that..?

Comment (humphd) [reply src/backend/web/graphql/index.js]:
```js
// v1
map(function(id) { return Post.byId(id) })

//v2
map(id => Post.byId(id));

// v3
const fn = id => Post.byId(id);
map(fn)

// v4
map(Post.byId)
```

Because `map` takes a function that accepts an `id` argument and transforms it into a Post, and since `Post.byId` is a function that accepts an `id` argument and transforms it into a Post, you can use it directly without calling it via an outer function.

Comment (c3ho) [reply src/backend/web/graphql/index.js]: TIL

File: src/backend/web/graphql/index.js (hunk 9 above)
Comment (c3ho) [reply src/backend/web/graphql/index.js]: Opting to do this in another PR.

**Comment by c3ho** [comment]
Kind of weird, 2020-01-01, 2020-01-02, 2020-01-03 don't work but 2020-01-04 does.
image

**Comment by c3ho** [comment]
Fixed slicing logic. I did a console.log of the length of array returned, the other dates worked because the results were less than 30, no issue as there was no pagination involved. 

results > 30 triggered my faulty slicing logic.

```
const pageResult = postIds.slice(
  page * perPage - 1 < 0 ? 0 : page * perPage,
  (page + 1) * prPage
);
```

if user sets page as 0 and perPage as 30, logic will now become
slice(0, 30)

if user sets page as 1 and perPage as 30, logic will now become
slice(30, 60)

**Comment by c3ho** [comment]
Merging as this was approved by both.
