### PR TITLE
Fixes #972 add title to Home page and move posts.length check into <Posts>

### LINKED ISSUE #972: Page title missing for Home
**What happened**:
The page title for `Home` is missing in Telescope's tab

**What should have happened**:
I should be able to see `Home` when I navigate to Telescope

**How to reproduce it (as precise as possible)**:
Go to `dev.telescope.cdot.systems` and check its tab

image

- OS: Linux
- Browser: Firefox, Chrome

### PR DESCRIPTION
**Pull request by cindyledev**
## Issue This PR Addresses
Fixes #972 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Re-adding title to home page. Moving code in #931 from index.js to Posts.jsx

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/src/pages/index.js [hunk 1]
```diff
@@ -92,16 +92,14 @@ export default function IndexPage() {
...
-        <Banner className="banner" />
-        <ScrollToTop />
-        <main className="main">
-          {posts.length > 0 ? <Posts posts={posts} /> : null}
-          {currentNumPosts !== initNumPosts ? <CustomizedSnackBar posts={currentNumPosts} /> : null}
-        </main>
-        <footer>© {new Date().getFullYear()}</footer>
-      </>
+    <PageBase title="Home">
+      <Banner className="banner" />
```
Comment (humphd) [inline src/frontend/src/pages/index.js:96]: You can remove `className` here, it's not doing anything.

File: src/frontend/src/pages/index.js [hunk 2]
```diff
@@ -92,16 +92,14 @@ export default function IndexPage() {
...
+      <ScrollToTop />
+      <main className="main">
```
Comment (humphd) [inline src/frontend/src/pages/index.js:98]: Same thing here, dump className, it's not being used.

File: src/frontend/src/pages/index.js [hunk 3]
```diff
@@ -92,16 +92,14 @@ export default function IndexPage() {
...
+        {posts.length > 0 ? <Posts posts={posts} /> : null}
```
Comment (humphd) [inline src/frontend/src/pages/index.js:99]: In a follow-up, we should move this check into `<Posts>` instead.

Comment (cindyledev) [reply src/frontend/src/pages/index.js:99]: I'm not 100% how to describe this in an issue. Maybe @c3ho is a better candidate to file the issue since he wrote this piece of the code.

Comment (cindyledev) [reply src/frontend/src/pages/index.js]: @humphd I made an attempt to move the check into `<Posts>`, can you review this PR again? Thanks

**Comment by cindyledev** [comment]
Ready for reviews

**Comment by c3ho** [comment]
Sorry, why did we move `index.js` stuff into `Posts`, I thought it was just a check?

File: src/frontend/src/components/Posts/Posts.jsx [hunk 4]
```diff
@@ -12,11 +14,65 @@ const useStyles = makeStyles({
...
+
+    savedCallback.current = callback;
+    // Polls every 5 minutes
+    const interval = setInterval(getCurrentNumPosts, 5 * 60 * 1000);
+    return () => clearInterval(interval);
+  }, [currentNumPosts]);
+
   return (
     <Container className={classes.root}>
+      {currentNumPosts !== initNumPosts ? <CustomizedSnackBar posts={currentNumPosts} /> : null}
```
Comment (c3ho) [inline src/frontend/src/components/Posts/Posts.jsx:75]: I think the only change that was needed was supposed to be somewhere here with the following line
{posts.length > 0 ? (do mapping here) : null}`

File: src/frontend/src/pages/index.js [hunk 5]
```diff
@@ -42,66 +38,12 @@ export default function IndexPage() {
...
-        <main className="main">
-          {posts.length > 0 ? <Posts posts={posts} /> : null}
-          {currentNumPosts !== initNumPosts ? <CustomizedSnackBar posts={currentNumPosts} /> : null}
-        </main>
-        <footer>© {new Date().getFullYear()}</footer>
-      </>
+    <PageBase title="Home">
+      <Banner />
+      <ScrollToTop />
+      <main>{posts.length > 0 ? <Posts posts={posts} /> : null}</main>
```
Comment (c3ho) [inline src/frontend/src/pages/index.js:45]: change this line from `{posts.length > 0 ? <Posts posts={posts} /> : null}` to ` <Posts posts={posts} />` since we'll be doing the check in `Posts` component

**Comment by cindyledev** [comment]
Sorry, I totally misunderstood what was being asked. I moved the `posts.lengths` check into `<Posts>` so this is ready for reviews again.
