### PR TITLE
Fix issue-1271 : Add BackToTopButton in searchPage

### LINKED ISSUE #1271: Long search results need the "Scroll to Top" component
When you do a search for posts, and get back lots of results, scrolling down doesn't show the up-arrow scroll-to-top widget like you get in the main timeline view.  Let's add it.

### PR DESCRIPTION
**Pull request by tianlangwu**
## Issue This PR Addresses
fix #1271 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [X] **UI**: Change which improves UI

## Description

Added Back to Top Button on the search page. A Back To Top button now shows up when you have a long search result on the search page. 
Added the css to move Back To Top Buttle to the top of the webpage. Please advise the position if you think that is better than move to the top. 
Thanks for your consideration!

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/src/components/SearchPage/SearchPage.jsx [hunk 1]
```diff
@@ -24,8 +33,11 @@ const SearchPage = () => {
     setFilterParam(filter);
   }
 
+  const classes = useStyles();
```
Comment (humphd) [inline src/frontend/src/components/SearchPage/SearchPage.jsx:36]: Move this to the very top of this function.

**Review by humphd — CHANGES_REQUESTED** [review]
One small change.

File: src/frontend/src/components/SearchPage/SearchPage.jsx [hunk 2]
```diff
@@ -1,14 +1,24 @@
...
+    top: 0,
+  },
+}));
 
 const SearchPage = () => {
   // We synchronize the `text` and `filter` values to the URL's query string
   // via `textParam` and `filterParam`. The <SearchBar> UI uses our internal
   // state values, and the <SearchResults> only update on page load or when
   // the user submits the form.
+  const classes = useStyles();
```
Comment (humphd) [inline src/frontend/src/components/SearchPage/SearchPage.jsx:21]: Sorry, above this comment:

```js
const SearchPage = () => {
  const classes = useStyles();

  // We synchronize the `text` and `filter` values to the URL's query string
  // via `textParam` and `filterParam`. The <SearchBar> UI uses our internal
  // state values, and the <SearchResults> only update on page load or when
  // the user submits the form.
  ...
```

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/frontend/src/components/SearchPage/SearchPage.jsx (hunk 2 above)
Comment (tianlangwu) [reply src/frontend/src/components/SearchPage/SearchPage.jsx:21]: oh, yes, My bad.

**Review by humphd — APPROVED** [review]

**Review by jossiey — APPROVED** [review]
It works as expected
