### PR TITLE
Fixes: 1595 - [next] Infinite Scrolling of Posts is broken (All of our infinite scrolls were broken)

### LINKED ISSUE #1595: [next] Infinite Scrolling of Posts is broken
**What happened**:

In #1504 we landed the new Posts, Post, and Timeline components for next.js.  The first page loads OK, but when you scroll down, the infinite scrolling isn't working correctly.  It looks like there is a ton of network activity (i.e., it's loading pages like it should) but it's not being updated in the UI.  I also think it's loading too much, so we may have a dependency issue with the hook that's loading things.

**What should have happened**:

You should be able to scroll down forever, like we can on Gatsby

**How to reproduce it (as precise as possible)**:

Go to https://telescope-next.netlify.app/, open your dev tools and the Network tab, and start scrolling down.  You'll get to the bottom and it won't keep working, but the network will go crazy loading pages.

We have a similar bug in the infinite scrolling for the search page, which could be connected, or just the same problem but a different cause.

cc @rogercyyu, @PedroFonsecaDEV.

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes #1595 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
 After landed the PR: https://github.com/Seneca-CDOT/telescope/pull/1573 created a bug inside our `LoadAutoScroll`'s useEffect both for our Gatsby and Next. This PR will fix the warning issue and fix all of our infinite scroll problems for Gatsby and Next (homepage and search page).

## Checklist

- [] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : Seem to be a quick fix, good job!

**Review by tonyvugithub — APPROVED** [review]

**Review by chrispinkney — APPROVED** [review]
LGTM

File: src/frontend/next/src/components/Posts/LoadAutoScroll.tsx [hunk 1]
```diff
@@ -44,12 +44,13 @@ function LoadAutoScroll({ onScroll }: Scroll) {
     return () => {
       observer.unobserve(buttonRefCopy as HTMLButtonElement);
     };
-  }, [$buttonRef, onScroll]);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (humphd) [inline src/frontend/next/src/components/Posts/LoadAutoScroll.tsx:47]: We should file a follow-up to figure out why our eslint doesn't like `[]` since I'd say it's a valid use case to not define deps, but want a one-time effect.
