### PR TITLE
issue-2423: Added state to store student quote

### LINKED ISSUE #2423: Student Quote changes on scroll
In #2422 we added a way for the student quote to be randomly changed on the front page.  However, it's not stable per load, and changes when I scroll the page (i.e., new random number is generated on re-render).

Steps to Reproduce:

1. Go to https://dev.telescope.cdot.systems/
2. Scroll down a few inches, then back up, then down
3. Notice the quote changes over and over again

We need to deal with this function and return value differently:

```js
const getQuote = () => {
  return quotes[Math.floor(Math.random() * quotes.length)];
};
```

We need that value to be stable across renders. cc @AmasiaNalbandian

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
fixes #2423

## Type of Change
This PR adds the sets a state for the student quote, so that when you scroll on the page, it doesn't grab a new quote to display. 

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/web/src/components/Banner.tsx [hunk 1]
```diff
@@ -110,18 +110,14 @@ type BannerProps = {
...
-
 export default function Banner({ onVisibilityChange }: BannerProps) {
   const classes = useStyles();
   const [gitInfo, setGitInfo] = useState({
     gitHubUrl: '',
     sha: '',
     version: '',
   });
-  const studentQuote = getQuote();
+  const [studentQuote] = useState(() => quotes[Math.floor(Math.random() * quotes.length)]);
```
Comment (humphd) [inline src/web/src/components/Banner.tsx:120]: Let's consider doing what @DukeManh suggested and move this out of the component.  Put it on line 113 above and do:

```ts
const studentQuote = quotes[Math.floor(Math.random() * quotes.length)]);
```

Then you can use it in the component, but it shouldn't change its value on re-render.

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/web/src/components/Banner.tsx (hunk 1 above)
Comment (AmasiaNalbandian) [reply src/web/src/components/Banner.tsx]: Perfect. I tried the solution but didn't quite understand we had to move it out, and it had not worked. This works now! Thank you.

**Review by humphd — APPROVED** [review]
👍

**Review by DukeManh — APPROVED** [review]
