### PR TITLE
Fix #1753 - Link author name to their feed URL

### LINKED ISSUE #1753: Author name links to feed instead of blog url
**What happened**:

When user clicks author name on post title, it should link to author's blog itself, not author's blog feed.
image

After clicking author name,
image

**What should have happened**:
But it should be something like this,
image

and after clicking author name, it should link to author's blog like this,

image

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS: Linux mint
- Browser: Firefox

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes #1753

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by HyperTHD — APPROVED** [review]

File: src/frontend/next/src/components/MyFeeds.tsx [hunk 1]
```diff
@@ -55,7 +55,7 @@ const MyFeeds = ({ user }: MyFeedsProps) => {
         const userFeeds = await response.json();
 
         const userFeedHash = userFeeds.reduce((hash: FeedHash, feed: Feed) => {
-          hash[feed.id] = { author: feed.author, url: feed.url };
+          hash[feed.id] = { author: feed.author, url: feed.url, link: feed.link };
```
Comment (manekenpix) [inline src/frontend/next/src/components/MyFeeds.tsx:58]: We don't need `url: feed.url` anymore, right? maybe we can delete it.

**Review by foxviet — APPROVED** [review]

File: src/frontend/next/src/components/MyFeeds.tsx (hunk 1 above)
Comment (DukeManh) [reply src/frontend/next/src/components/MyFeeds.tsx:58]: @manekenpix I thought so too, but the hash is then passed to `ExistingFeedList` where the RSS feed URL is needed.

**Review by birtony — APPROVED** [review]
Good job @DukeManh!

**Review by foxviet — APPROVED** [review]

**Review by birtony — APPROVED** [review]
