### PR TITLE
Fixes #1252, Added Comments for Logger Discussion

### LINKED ISSUE #1252: Reduce log spam
Our logging is great, but too noisy by default.  It's nice to log all kinds of things re: feed parsing and network errors, but they fill the log with spam that doesn't matter when you're developing or trying to debug a problem on production.

Our logger, Pino, has these levels:

```
  trace: 'DEBUG',
  debug: 'DEBUG',
  info: 'INFO',
  warn: 'WARNING',
  error: 'ERROR',
  fatal: 'CRITICAL',
```

For production, we probably only care about error/critical, and for normal development, probably only info and up.

Let's audit our logging calls and change the level we use.  Especially for the places where we do feed logging, let's make that `debug` or something vs. `info`.

### PR DESCRIPTION
**Pull request by Metropass**
## Issue This PR Addresses
Fixes #1252 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

So, I wanted to make this PR to discuss what needs to be changed for the Backend's logger. 
I've done an audit and added comments to the code on what I personally think needs to be changed, and why. 
I would really like some feedback/discussions so that what we change will be useful, and won't omit any data when debugging Telescope.

* `shutdown.js`
[There ](https://github.com/Seneca-CDOT/telescope/blob/c7a532038950ea2d039a8de8682046300b30db10/src/backend/lib/shutdown.js#L18)seems to be a lot of `error` functions being invoked when the service is shutdown. We parse the error into the logger, and mention that the shutdown was not graceful & dirty. Is it possible to move this into debug? 

* `processor.js`
-[Inside](https://github.com/Seneca-CDOT/telescope/blob/c7a532038950ea2d039a8de8682046300b30db10/src/backend/feed/processor.js#L145), we have a lot of warnings being sent to the logger. I think that the `info` calls are appropriate, but should we change the warnings into debug, and return a generic message for production? 

- [On Line 135](https://github.com/Seneca-CDOT/telescope/blob/c7a532038950ea2d039a8de8682046300b30db10/src/backend/feed/processor.js#L135), we send some data into `info` mentioning that a certain feed as been skipped. It might be redundant to print this all the time, as the larger the ignored feed list grows, the more messages this will output. Should we change this into debug?

- [Line 110](https://github.com/Seneca-CDOT/telescope/blob/c7a532038950ea2d039a8de8682046300b30db10/src/backend/feed/processor.js#L110), we only check for an instance of `ArticleError`, to let out service continue. Should we add a debug call to this, for developers to see what type of error is thrown?

These were the log calls that I think should be changed, I'm a little bit iffy on changing any calls within `backend/web`, as they're appropriate (in terms of logging any errors that occur).

I would love to get feedback on what needs to be changed.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by HyperTHD** [comment]
Move all your comments to the side instead of directly below the catch to avoid all these linting errors

**Comment by Metropass** [comment]
> Move all your comments to the side instead of directly below the catch to avoid all these linting errors

I'm aware there's some errors, I'm not trying to pass the tests atm until we figure out what to change

**Comment by yuanLeeMidori** [comment]
@Metropass These are my thoughts,

- showdown
I agree it is not that necessary for error, maybe warn?
- processor
I'm not sure about this, the not-found or error log should be different from the general ones?
- line 135
I agree with you, skipping feeds might be more useful in debug level instead of info
- line 110
adding it to debug sounds good
--- 

I'm still looking for possibility if there is any error log can be moved to critical and warning. I'll append them in this PR if I have progress.

File: src/backend/feed/processor.js [hunk 1]
```diff
@@ -107,6 +107,7 @@ function articlesToPosts(articles, feed) {
     articles.map(async (article) => {
       try {
         await Post.createFromArticle(article, feed);
+        //Add a debug log to see what is thrown?
```
Comment (humphd) [inline src/backend/feed/processor.js:110]: We end up logging this in the caller on line 214, and that one could probably be turned into a warning vs. error.

File: src/backend/feed/processor.js [hunk 2]
```diff
@@ -132,10 +133,12 @@ module.exports = async function processor(job) {
   let info;
   const [invalid, delayed] = await Promise.all([feed.isInvalid(), feed.isDelayed()]);
   if (invalid) {
+    //Debug?
     logger.info(`Skipping resource at ${feed.url}. Feed previously marked invalid`);
```
Comment (humphd) [inline src/backend/feed/processor.js:137]: I think info is right here, since we'd want to see skipped feeds in production.

File: src/backend/feed/processor.js [hunk 3]
```diff
@@ -132,10 +133,12 @@ module.exports = async function processor(job) {
...
     return;
   }
   if (delayed) {
+    //Debug?
     logger.info(`Skipping resource at ${feed.url}. Feed previously marked for delayed processing`);
```
Comment (humphd) [inline src/backend/feed/processor.js:142]: Same, leave this one info

File: src/backend/feed/processor.js [hunk 4]
```diff
@@ -144,6 +147,7 @@ module.exports = async function processor(job) {
     // If we get no new version info, there's nothing left to do.
     if (!info.shouldDownload) {
       // Log some common cases we see, with a general message if none of these
+      //A lot of warnings & info, should we change it?
```
Comment (humphd) [inline src/backend/feed/processor.js:150]: These are all useful for debugging, I'd leave them.

File: src/backend/feed/worker.js [hunk 5]
```diff
@@ -33,6 +33,7 @@ exports.start = async function () {
     logger.info('Connected to elasticsearch!');
 
     const concurrency = getFeedWorkersCount();
+    //Change into debug?
```
Comment (humphd) [inline src/backend/feed/worker.js:36]: Yeah, debug, agree.

File: src/backend/lib/shutdown.js [hunk 6]
```diff
@@ -11,6 +11,7 @@ async function stopQueue() {
     await feedQueue.close();
     logger.info('Feed queue shut down.');
   } catch (error) {
+    //Change to debug?
```
Comment (humphd) [inline src/backend/lib/shutdown.js:14]: Agree, debug here.

File: src/backend/lib/shutdown.js [hunk 7]
```diff
@@ -24,6 +25,7 @@ async function stopWebServer() {
     await serverClose();
     logger.info('Web server shut down.');
   } catch (error) {
+    // Change to debug?
```
Comment (humphd) [inline src/backend/lib/shutdown.js:28]: Yeah, debug for sure.

File: src/backend/lib/shutdown.js [hunk 8]
```diff
@@ -33,6 +35,7 @@ async function cleanShutdown() {
     await Promise.all([stopQueue(), stopWebServer()]);
     logger.info('Completing shut down.');
   } catch (error) {
+    //Change to debug? Shutsdown, but dirty
```
Comment (humphd) [inline src/backend/lib/shutdown.js:38]: Agree, debug.

**Review by humphd — CHANGES_REQUESTED** [review]

**Review by humphd — COMMENTED** [review]
You've got both branches in here, please separate this work from the other.

File: package.json [hunk 9]
```diff
@@ -82,6 +82,7 @@
     "body-parser": "1.19.0",
     "bull": "3.20.1",
     "bull-board": "1.3.1",
+    "clean-whitespace": "0.1.2",
```
Comment (chrispinkney) [inline package.json:85]: What's the point of this? Ah, from the merge?

Comment (Metropass) [reply package.json]: Yup, it's cleaned out now :)

**Review by chrispinkney — DISMISSED** [review]
Lookin' good!

**Review by humphd — DISMISSED** [review]

**Review by yuanLeeMidori — APPROVED** [review]

**Review by PedroFonsecaDEV — APPROVED** [review]

**Review by tonyvugithub — APPROVED** [review]

**Review by HyperTHD — APPROVED** [review]

**Review by birtony — APPROVED** [review]
