### PR TITLE
Fix #2486: build log for autodeployment is not working

### LINKED ISSUE #2486: Build log for autodeployment is not working properly
**What happened**:
Mismatch object shape. The script expects the response to have a `started` key...
https://github.com/Seneca-CDOT/telescope/blob/3131812c364e551b697c123aa9a66df695b9e723/src/api/status/public/js/build-log/api.js#L6-L19
... but the server response
https://github.com/Seneca-CDOT/telescope/blob/3131812c364e551b697c123aa9a66df695b9e723/tools/autodeployment/builds.js#L46-L53

**What should have happened**:
The script should check for key `current` and grab value of `current.startedDate`

**How to reproduce it (as precise as possible)**:
- Go to https://dev.api.telescope.cdot.systems/v1/status/pages/build.html
- Open DevTools > Network
- See the shape of the server response
image

**Anything else we need to know?**:

**Environment**:

- OS: Window 11
- Browser: Chrome 96

### PR DESCRIPTION
**Pull request by Andrewnt219**
## Issue This PR Addresses

Fixes #2486

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Fix build log doesn't parse the data correctly, so it always returns false (i.e. no on-going build).
- Change files structure to align with other scripts.

image
image

## Test plan

- Change autodeploymentUrl in public/js/buildl-log/api.js
```diff
- const autodeploymentUrl = (path) => `//${location.hostname}:4000/${path}`;
+ const autodeploymentUrl = (path) => `//dev.api.telescope.cdot.systems:4000/${path}`;  
```
- Allow all src in src/server.js
```diff
-         connectSrc: [
-          "'self'",
-          '*.fontawesome.com',
-          `${host.replace(/(^\w+:|^)\/\//, '')}:4000`,
-          '*.github.com',
-        ],
+ connectSrc: ["'self'", "*"]
```
- Go to /src/api/status.
- Run `npm run dev`
- Go to pages/build.html
- Build log only shows up if there is an on-going build

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/api/status/public/js/build-log/api.js [hunk 1]
```diff
@@ -3,19 +3,23 @@ const autodeploymentUrl = (path) => `//${location.hostname}:4000/${path}`;
 
 export const checkBuildStatus = async () => {
   try {
-    const res = await fetch(autodeploymentUrl('status'));
+    const res = await fetch(autodeploymentUrl('status'), {
+      headers: {
+        'Cache-Control': 'no-cache',
+      },
+    });
```
Comment (manekenpix) [inline src/api/status/public/js/build-log/api.js:10]: Should we do this for the log route too?
```js
const res = await fetch(autodeploymentUrl('log'));
```

**Review by manekenpix — DISMISSED** [review]

File: src/api/status/public/js/build-log/api.js [hunk 2]
```diff
@@ -3,19 +3,23 @@ const autodeploymentUrl = (path) => `//${location.hostname}:4000/${path}`;
 
 export const checkBuildStatus = async () => {
   try {
-    const res = await fetch(autodeploymentUrl('status'));
+    const res = await fetch(autodeploymentUrl('status'), {
+      headers: {
+        'Cache-Control': 'no-cache',
```
Comment (humphd) [inline src/api/status/public/js/build-log/api.js:8]: This needs to happen on the response vs. request.  Do this in the autodeployment server here: https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/builds.js#L100-L129

You can add this to each of those before you send the result:

```js
res.setHeader('Cache-Control', 'no-cache');
```

Comment (humphd) [reply src/api/status/public/js/build-log/api.js:8]: NOTE: this can (and probably should) happen in a separate PR so we don't block this work.  I would just remove the bit above to add headers here for now, and do a second PR.

**Review by humphd — CHANGES_REQUESTED** [review]
This is amazing to see!

File: src/api/status/public/js/build-log/api.js (hunk 2 above)
Comment (Andrewnt219) [reply src/api/status/public/js/build-log/api.js]: Ok, I'll make another PR today.

**Review by humphd — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]

**Review by humphd — APPROVED** [review]
@Andrewnt219 nice job, go ahead and merge this yourself

**Comment by Andrewnt219** [comment]
Should have done a "squash and merge". "Rebase and merge" took my commit as a title instead of the PR's title.
