### PR TITLE
Fixes #2442: Fixes linking of users icon, and adds title to users and telescope avatar icons

### LINKED ISSUE #2442: Add tooltip title to TelescopeAvatar, use with GitHub User component
In #2430 we're adding a GitHub user avatar.  We want to be able to pass down the username and have it be used as a `title` attribute, so you can hover and see the name.

In https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/components/TelescopeAvatar.tsx#L49 it looks like it's setting `alt` but not `title`.  Let's fix that, then use it for all the places we use the TelescopeAvatar component.

### PR DESCRIPTION
**Pull request by HyperTHD**
## Issue This PR Addresses
I wanna say this PR should close #2442 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This PR addresses how the user component was linking to user's github pages. It originally used `window.open()`, instead of an href which is typically how this is done. This PR fixes that. This PR also adds a tooltip title to the user icons, as well as the Telescope Avatar icon as well to keep consistency.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2447"></a>

### CODE REVIEW

File: src/web/src/components/Posts/Users.tsx [hunk 1]
```diff
@@ -57,14 +57,13 @@ const Users = ({ usernames, avatarSize = 25 }: Props) => {
...
             <div>
-              <TelescopeAvatar
-                img={getUserImage(user, avatarSize)}
-                size={`${avatarSize}px`}
-                name={user}
-                action={() => {
-                  window.open(`https://github.com/${user}`, '_blank');
-                }}
-              />
+              <a href={`https://github.com/${user}`}>
```
Comment (humphd) [inline src/web/src/components/Posts/Users.tsx:60]: Let's make our avatar's a bit more consistent.  Both support wrapping in an `<a>`, but the prop is named differently: `TelescopeAvatar` wants it as a `blog` and `PostAvatar` wants it as `url`.  Can we standardize on `url` or `href` or something in both cases?

And here, let's not wrap the `TelescopeAvatar` in an `<a>`, let's do it in the component.

**Review by humphd — CHANGES_REQUESTED** [review]

**Review by humphd — APPROVED** [review]
Way better for accessibility, nice work.

**Review by AmasiaNalbandian — APPROVED** [review]
LGTM! I like that we have the hover on the post avatars too now.

**Comment by AmasiaNalbandian** [comment]
mspaint_s1HGnpxfVG
mspaint_LCRtzTqOVs
mspaint_V0acm0JPtT
