### PR TITLE
Fix #2278: Classnames from snapshots created locally does not matches with the ones created on CI/CD.

### LINKED ISSUE #2278: (Front end)Classnames from snapshots created locally does not matches with the ones created on CI/CD.
**What happened**:
Our CI/CD is failing when comparing front-end snapshots from our components. The `class names` generated by MUI don't match:

```
FAIL src/web/src/components/AboutFooter.test.tsx
  ✕ renders correctly (144 ms)

  ● renders correctly

    expect(received).toMatchSnapshot()

    Snapshot name: `renders correctly 1`

    - Snapshot  - 2
    + Received  + 2

    @@ -4,14 +4,14 @@
        >
          <div
            class="MuiBox-root MuiBox-root-8"
          >
            <div
    -         class="MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-flex-start MuiGrid-justify-xs-space-between"
    +         class="MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-flex-start MuiGrid-justify-content-xs-space-between"
            >
              <div
    -           class="MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-justify-xs-center MuiGrid-grid-xs-12"
    +           class="MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-justify-content-xs-center MuiGrid-grid-xs-12"
              >
                <img
                  alt="Telescope Logo"
                  height="60"
                  src="/logo.svg"

       8 | it('renders correctly', () => {
       9 |   const { asFragment } = render(<AboutFooter />);
    > 10 |   expect(asFragment()).toMatchSnapshot();
         |                        ^
      11 | });
      12 |

      at Object.<anonymous> (src/web/src/components/AboutFooter.test.tsx:10:24)
```

**What should have happened**:
The class names should be the same on our local machines and in our CI/CD.

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes #2278

What is happening: 

Running locally `npm i`, we install MUI version `4.11.3` while our CI/CD install MUI version `4.12.3`.
`4.11` and `4.12` versions have a different name convention regarding some MUI components we use(in this case, we are using their `<Grid>` component).

That's the reason why our snapshots are failing. 

I advise us to enforce MUI `4.11.3` instead of moving forward to `4.12.3` for now. 
Because: 
-Right now, we don't have enough people to cover our codebase and check if our front-end will render exactly as we expect with MUI `4.12.3`. 
-Since we only have two small snapshots tests in our front-end, and it will need a lot more tests, I don't see any reason to keep our CI/CD failing in those two snapshots for now. 

But we need to keep an eye on MUI because they are currently working on MUI version 5. 

Again this is just a temporary fix until we find a better solution. 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/web/src/components/AboutFooter.tsx [hunk 1]
```diff
@@ -1,56 +1,58 @@
...
-    flexGrow: 1,
-    backgroundColor: theme.palette.primary.main,
-    padding: '2rem',
-  },
-  heading: {
-    color: theme.palette.primary.contrastText,
-    [theme.breakpoints.down('md')]: {
-      marginTop: '2rem',
+const useStyles = makeStyles((theme) =>
+  createStyles({
```
Comment (manekenpix) [inline src/web/src/components/AboutFooter.tsx:9]: Quick question: since the problem is the MUI version, do we need to use `createStyles` here?

Comment (PedroFonsecaDEV) [reply src/web/src/components/AboutFooter.tsx:9]: @manekenpix 
Follow the [docs](https://material-ui.com/guides/typescript/#using-createstyles-to-defeat-type-widening).
Please let me know what do you think.

**Review by manekenpix — APPROVED** [review]
