### PR TITLE
Handle Telescope user registration and login

### LINKED ISSUE #2735: Connect Supabase with our SSO login flow
**What happened**:

Part of #2555, once we config supabase and have it running, we want to make the `Auth` service communicate with the Supabase through the [supabase-js](https://www.npmjs.com/package/@supabase/supabase-js) package to handle new user registration and login.

**How to reproduce it (as precise as possible)**:
- OS:
- Browser:

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes #2735  

This makes SSO service use Supabase for Telescope user registration.
The SSO service uses a admin `SERVICE_ROLE` key to initiate Supabase connection and do db queries.

When users log in through Seneca SSO, we use the passed user info and look them up in the `telescope_profiles` table, if there is an entry, they are registered Telescope users.

Things need to happen

- [ ] Update SSO tests to use Supabase
- [ ] Enable Row Level Security on Telescope_users, probably depends on #1871 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
I have a question about this approach.  Won't this limit us with respect to row level security?  We'll have user data, but not users as Supabase understands them (i.e., it won't be aware of these users).  The downside of this is that we can't leverage the user-level security Supabase grants us on the other databases in the project.

I've been trying to sort out the right way to do this, and my current research involves:

- asking https://github.com/supabase/supabase/discussions/5043
- looking at doing password-less user creation via an API call https://github.com/supabase/supabase/issues/1176
- using Supabase's JWT to get row-level security when doing custom auth and direct access https://medium.com/@gracew/using-supabase-rls-with-a-custom-auth-provider-b31564172d5d

@DukeManh, can you look at the above and give me your take?  I wonder if we can adapt what you're doing here to include some of these.

Also, I note that this basically removes the need for the users service.  We should consider if that's what we want.  For example: using the SSO service to query for all users + feeds seems wrong to me.

**Comment by DukeManh** [comment]
@humphd, I've read and really liked [the third link ](https://medium.com/@gracew/using-supabase-rls-with-a-custom-auth-provider-b31564172d5d). From my understanding, this is what we could do to enforce Row Level Security.

- We use a `JWT_SECRET` (shared between SSO and Supabase) to sign the user info and send back the token to the client
- The client calls `supabase.auth.setAuth(token)`. Because the JWT_Secret is shared between SSO and Supabase, the user is authenticated.
- With Supabase, we can add a policy that looks at `request.jwt.roles` or `request.jwt.id` to determine if they are allowed to do something with the database.

> using the SSO service to query for all users + feeds seems wrong to me.

The SSO service only queries for uses for authentication. We could make separate feeds table from profiles?

File: docker/supabase/volumes/db/init/04-initiate-tables.sql [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+CREATE TABLE IF NOT EXISTS telescope_profiles (
+  id text PRIMARY KEY,
+  registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
+  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
+  feeds text[] NOT NULL,
+  display_name citext UNIQUE NOT NULL,
+  first_name text NOT NULL,
+  last_name text NOT NULL,
+  email citext UNIQUE NOT NULL,
```
Comment (humphd) [inline docker/supabase/volumes/db/init/04-initiate-tables.sql:11]: https://github.com/Seneca-CDOT/telescope/blob/master/docker/supabase/volumes/db/init/01-auth-schema.sql#L11

File: docker/supabase/volumes/db/init/04-initiate-tables.sql [hunk 2]
```diff
@@ -0,0 +1,14 @@
+CREATE extension IF NOT EXISTS citext  WITH SCHEMA extensions;
+
+CREATE TABLE IF NOT EXISTS telescope_profiles (
+  id text PRIMARY KEY,
+  registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
+  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
+  feeds text[] NOT NULL,
```
Comment (humphd) [inline docker/supabase/volumes/db/init/04-initiate-tables.sql:7]: I wonder if we should move this to a separate table (follow-up PR) with a foreign key relationship on the `id` for the user?  The idea of a user having feeds is something that could change, it's not really part of your profile.

File: docker/supabase/volumes/db/init/04-initiate-tables.sql [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  display_name citext UNIQUE NOT NULL,
+  first_name text NOT NULL,
+  last_name text NOT NULL,
+  email citext UNIQUE NOT NULL,
+  github_username citext UNIQUE NOT NULL,
+  github_avatar_url citext UNIQUE NOT NULL
```
Comment (humphd) [inline docker/supabase/volumes/db/init/04-initiate-tables.sql:13]: Do you think we need to store this, since we can construct it from the user's GitHub username?

Also, I'm not sure about case insensitive values for a URL.

File: src/api/sso/src/authentication.js [hunk 4]
```diff
@@ -120,23 +119,24 @@ const strategy = new SamlStrategy(
...
-          }
+        const { data: profiles, error } = await supabase
+          .from('telescope_profiles')
+          .select('*')
+          .eq('id', id);
+
+        if (error) {
           // We can't get a response from the Users service, so we don't know what we have.
-          throw new Error(`unable to get user info from Users service: ${res.status}`);
+          throw new Error(`unable to get user info from Users service: ${error.message}`);
```
Comment (humphd) [inline src/api/sso/src/authentication.js:129]: from Supabase

File: src/api/sso/src/authentication.js [hunk 5]
```diff
@@ -120,23 +119,24 @@ const strategy = new SamlStrategy(
...
-          if (res.status === 404) {
-            // No Telescope user profile found, so create a regular Seneca user
-            logger.debug({ senecaProfile }, `No Telescope account for ${id} with Users service`);
-            done(null, new User(senecaProfile));
-            return;
-          }
+        const { data: profiles, error } = await supabase
+          .from('telescope_profiles')
+          .select('*')
+          .eq('id', id);
```
Comment (humphd) [inline src/api/sso/src/authentication.js:125]: `.limit(1)` ? https://supabase.com/docs/reference/javascript/limit

File: src/api/sso/src/middleware.js [hunk 6]
```diff
@@ -88,59 +88,62 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
-        headers: {
-          // re-use the user's authorization header and token
-          Authorization: req.get('Authorization'),
-        },
-      });
+    const id = getUserId(req);
+    const { data: profiles, error } = await supabase
+      .from('telescope_profiles')
+      .select('*')
+      .eq('id', id);
```
Comment (humphd) [inline src/api/sso/src/middleware.js:132]: `.limit(1)`?

**Review by humphd — CHANGES_REQUESTED** [review]

**Comment by humphd** [comment]
> @humphd, I've read and really liked [the third link ](https://medium.com/@gracew/using-supabase-rls-with-a-custom-auth-provider-b31564172d5d). From my understanding, this is what we could do to enforce Row Level Security.
> 
> * We use a `JWT_SECRET` (shared between SSO and Supabase) to sign the user info and send back the token to the client
> * The client calls `supabase.auth.setAuth(token)`. Because the JWT_Secret is shared between SSO and Supabase, the user is authenticated.
> * With Supabase, we can add a policy that looks at `request.jwt.roles` or `request.jwt.id` to determine if they are allowed to do something with the database.

cc @joelazwar, we should capture the above in the other Supabase/Login/SSO issues we have filed and implement it.

> > using the SSO service to query for all users + feeds seems wrong to me.
> 
> The SSO service only queries for uses for authentication. We could make separate feeds table from profiles?

Yeah, I think that's correct.

File: docker/supabase/volumes/db/init/04-initiate-tables.sql (hunk 1 above)
Comment (DukeManh) [reply docker/supabase/volumes/db/init/04-initiate-tables.sql:10]: We could do this but later we'll have to call `toLower` to make sure the email is unique because emails are case-insensitive.

File: docker/supabase/volumes/db/init/04-initiate-tables.sql (hunk 3 above)
Comment (DukeManh) [reply docker/supabase/volumes/db/init/04-initiate-tables.sql]: GitHub uses user id for avatars now, @humphd's avatar  https://avatars.githubusercontent.com/u/427398?v=4

Comment (DukeManh) [reply docker/supabase/volumes/db/init/04-initiate-tables.sql]: Changed the URL from citext to text.

**Comment by DukeManh** [comment]
@joelazwar will help me with fixing the failing tests.

File: src/api/sso/src/middleware.js [hunk 7]
```diff
@@ -85,62 +85,88 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
+      displayName,
+      feeds,
+      github: { username: githubUserName, avatarUrl: githubAvatarUrl },
+    } = req.body;
 
-      next();
-    } catch (err) {
-      logger.error({ err }, 'error creating Telescope user');
-      next(createError(500, 'unable to create Telescope user'));
+    console.log('creator');
```
Comment (DukeManh) [inline src/api/sso/src/middleware.js:100]: oops

File: docker/supabase/volumes/db/init/04-initiate-tables.sql (hunk 1 above)
Comment (humphd) [reply docker/supabase/volumes/db/init/04-initiate-tables.sql:10]: I don't think we care, do we?  The email is informational only.  The hashed email (`id`) is all we really care about.  But either way is fine.

File: docker/supabase/volumes/db/init/04-initiate-tables.sql [hunk 8]
```diff
@@ -0,0 +1,20 @@
...
+  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
+  display_name citext UNIQUE NOT NULL,
+  first_name text NOT NULL,
+  last_name text NOT NULL,
+  email citext UNIQUE NOT NULL,
+  github_username citext UNIQUE NOT NULL,
+  github_avatar_url text NOT NULL
+);
+
+CREATE TABLE IF NOT EXISTS feeds (
```
Comment (humphd) [inline docker/supabase/volumes/db/init/04-initiate-tables.sql:15]: Nice.

File: src/api/sso/src/authentication.js [hunk 9]
```diff
@@ -116,27 +115,29 @@ const strategy = new SamlStrategy(
...
-        if (!res.ok) {
-          if (res.status === 404) {
-            // No Telescope user profile found, so create a regular Seneca user
-            logger.debug({ senecaProfile }, `No Telescope account for ${id} with Users service`);
-            done(null, new User(senecaProfile));
-            return;
-          }
-          // We can't get a response from the Users service, so we don't know what we have.
-          throw new Error(`unable to get user info from Users service: ${res.status}`);
+        const { data: profiles, error } = await supabase
```
Comment (humphd) [inline src/api/sso/src/authentication.js:122]: Does Supabase still return an array if you do `limit(1)`?

File: src/api/sso/src/authentication.js [hunk 10]
```diff
@@ -116,27 +115,29 @@ const strategy = new SamlStrategy(
...
+          .from('telescope_profiles')
+          .select('*')
+          .eq('id', id)
+          .limit(1);
+
+        if (error) {
+          // We can't get a response from the Supabase, so we don't know what we have.
+          throw new Error(`unable to get user info from Supabase: ${error.message}`);
+        }
+        if (!profiles.length) {
```
Comment (humphd) [inline src/api/sso/src/authentication.js:132]: Wondering about this with `.limit(1)`, if it still sends an array?

File: src/api/sso/src/middleware.js (hunk 7 above)
Comment (humphd) [reply src/api/sso/src/middleware.js:100]: Yeah, remove this.

**Review by Kevan-Y — APPROVED** [review]
Tested locally. LGTM

File: src/api/sso/src/middleware.js [hunk 11]
```diff
@@ -85,62 +85,88 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
+    if (userError) {
+      logger.warn(
+        { code: userError.code, details: userError.details, id, data: req.body },
+        userError.message
+      );
+      next(createError(400, 'unable to create user'));
+      return;
+    }
+
+    const { error: feedError } = await supabase.from('feeds').insert(
```
Comment (humphd) [inline src/api/sso/src/middleware.js:123]: Can we run these two inserts in parallel vs `awaiting` both like this in sequence?

File: src/api/sso/src/middleware.js [hunk 12]
```diff
@@ -85,62 +85,88 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
+      feeds.map((feedUrl) => ({
+        user_id: id,
+        feed_url: feedUrl,
+        // TODO: Allow adding Youtube/Twitch feed
```
Comment (humphd) [inline src/api/sso/src/middleware.js:127]: Please file an issue on this so we don't lose track.  cc @dbelokon, @sirinoks.

File: src/api/sso/src/middleware.js [hunk 13]
```diff
@@ -85,62 +85,88 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
+      })),
+      { returning: 'minimal' }
+    );
+
+    if (feedError) {
+      logger.warn(
+        { code: feedError.code, details: feedError.details, id, data: req.body },
+        feedError.message
+      );
+      await supabase.from('telescope_profiles').delete({ returning: 'minimal' }).match({ id });
```
Comment (humphd) [inline src/api/sso/src/middleware.js:138]: This needs some explanation.  Can we avoid this situation altogether?  Or if we have to do this, we should explain it with a comment.

File: src/web/src/components/NavBar/index.tsx [hunk 14]
```diff
@@ -75,6 +75,11 @@ const useStyles = makeStyles((theme) => ({
   },
   avatar: {
     padding: '12px',
+    background: 'none',
```
Comment (humphd) [inline src/web/src/components/NavBar/index.tsx:78]: What is this bit doing here?

**Review by humphd — CHANGES_REQUESTED** [review]
I think this is pretty close.

File: src/api/sso/src/authentication.js (hunk 9 above)
Comment (DukeManh) [reply src/api/sso/src/authentication.js:122]: Yes, still an array.

File: src/web/src/components/NavBar/index.tsx (hunk 14 above)
Comment (DukeManh) [reply src/web/src/components/NavBar/index.tsx:78]: In the Eslint fix PR I made because of configuration, I wrapped every buttons in a `button` element and it created unwanted styles for them. 
This is not related yeah, should I keep it?

Comment (humphd) [reply src/web/src/components/NavBar/index.tsx:78]: It's not critical, you can leave it.  But, try not to do this when you can put it in a follow-up.

File: src/api/sso/src/middleware.js (hunk 11 above)
Comment (DukeManh) [reply src/api/sso/src/middleware.js:123]: People are requesting this feature https://github.com/supabase/supabase/discussions/526

File: src/web/src/components/NavBar/index.tsx (hunk 14 above)
Comment (humphd) [reply src/web/src/components/NavBar/index.tsx:78]: The reason being: anything that will slow down this review should be avoided, it's already a lot.

File: src/api/sso/src/authentication.js [hunk 15]
```diff
@@ -116,27 +115,29 @@ const strategy = new SamlStrategy(
...
-          throw new Error(`unable to get user info from Users service: ${res.status}`);
+        const { data: profiles, error } = await supabase
+          .from('telescope_profiles')
+          .select('*')
+          .eq('id', id)
+          .limit(1);
+
+        if (error) {
+          // We can't get a response from the Supabase, so we don't know what we have.
+          throw new Error(`unable to get user info from Supabase: ${error.message}`);
```
Comment (humphd) [inline src/api/sso/src/authentication.js:130]: I'm running the e2e tests locally, and I'm falling into this error constantly.

In the logs for the SSO container, I see:

```
Error: unable to get user info from Supabase: relation "public.telescope_profiles" does not exist
```

It appears that we have a permissions issue.  My limited research into this says that we need to create the `telescope_profiles` table with the `public` schema, so we can access it via the client like this.

From https://www.postgresqltutorial.com/postgresql-schema, it appears that this table should already be in the `public` schema.  Which leads me to think that your tables aren't created, and that you `.sql` file isn't being run.  going to http://localhost:8910/project/default/editor I can see the `auth` schema and tables, but nothing in `public`.

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/api/sso/src/authentication.js (hunk 15 above)
Comment (humphd) [reply src/api/sso/src/authentication.js:130]: I looked inside the `supabase/postgres` container, and I can see the file:

```sh
root@59c20334c37b:/docker-entrypoint-initdb.d# ls -lah
total 32K
drwxr-xr-x 7 root root  224 Feb  9 15:26 .
drwxr-xr-x 1 root root 4.0K Feb  4 23:07 ..
-rw-r--r-- 1 root root 2.5K Feb  2 00:55 00-initial-schema.sql
-rw-r--r-- 1 root root 4.8K Feb  2 00:55 01-auth-schema.sql
-rw-r--r-- 1 root root 4.3K Feb  2 00:55 02-storage-schema.sql
-rw-r--r-- 1 root root 2.8K Feb  2 00:55 03-post-setup.sql
-rw-r--r-- 1 root root  736 Feb  9 15:26 04-initiate-tables.sql
```

So why is it not there?

Comment (DukeManh) [reply src/api/sso/src/authentication.js:130]: This is weird. I tried running it again locally and I can see `telescope_profiles` and `feeds` tables in public.

image


Screen Shot 2022-02-09 at 12 15 57 PM

Comment (humphd) [reply src/api/sso/src/authentication.js:130]: Destroyed and re-created the `supabase-db` container, and I can confirm that it's now running the 4th script and creating these tables:

Screen Shot 2022-02-09 at 2 18 30 PM

While I was doing this, I noticed that row level security (RLS) is not on for these tables.  In a follow-up, we should think about adding.

Comment (DukeManh) [reply src/api/sso/src/authentication.js:130]: Yeah, it depends on #1871 to get the JWT payload from requests.

**Comment by DukeManh** [comment]
I will keep a minimal `feeds` table in this PR so as to save users' feeds from the user registration flow. Updating the schema can happen in #2860.

File: src/api/sso/src/middleware.js (hunk 13 above)
Comment (DukeManh) [reply src/api/sso/src/middleware.js:138]: I need to save the user in first to reference the user_id. If feed URLs already exist we want to delete the created user.

**Comment by humphd** [comment]
It's amazing this is passing the tests, so it must have been a stuck container on my local machine!  You can delete the code that is failing eslint checks, and @joelazwar can add it as part of the work on our SSO + Supabase.

```
> @senecacdot/telescope@2.6.1 eslint /home/runner/work/telescope/telescope
> eslint --config .eslintrc.js "**/*.{jsx,tsx,ts,js}"


/home/runner/work/telescope/telescope/src/api/sso/test/e2e/signup-flow.test.js
Error:     7:16  error  'logout' is assigned a value but never used  no-unused-vars
Error:   146:13  error  'id' is assigned a value but never used      no-unused-vars
Error:   146:17  error  'token' is assigned a value but never used   no-unused-vars

✖ 3 problems (3 errors, 0 warnings)

 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

File: config/env.development [hunk 16]
```diff
@@ -289,11 +289,11 @@ SITE_URL=http://localhost:8000
 
 ADDITIONAL_REDIRECT_URLS=
 JWT_EXPIRY=3600
-DISABLE_SIGNUP=false
+DISABLE_SIGNUP=true
```
[the remark this answers is not in the document]
Comment (DukeManh) [reply config/env.development:292]: Correcto

File: config/env.development [hunk 17]
```diff
@@ -289,11 +289,11 @@ SITE_URL=http://localhost:8000
...
 
 ## Email auth
-ENABLE_EMAIL_SIGNUP=true
-ENABLE_EMAIL_AUTOCONFIRM=true
+ENABLE_EMAIL_SIGNUP=false
+ENABLE_EMAIL_AUTOCONFIRM=false
```
[the remark this answers is not in the document]
Comment (DukeManh) [reply config/env.development:296]: correcto

File: src/api/sso/src/middleware.js [hunk 18]
```diff
@@ -85,62 +85,82 @@ module.exports.captureAuthDetailsOnSession = function captureAuthDetailsOnSessio
...
+      );
+      next(createError(400, 'unable to create user'));
+      return;
+    }
+
+    const { error: feedError } = await supabase.from('feeds').insert(
+      feeds.map((feedUrl) => ({
+        user_id: id,
+        feed_url: feedUrl,
+        // TODO: Allow adding Youtube/Twitch feed
```
Comment (humphd) [inline src/api/sso/src/middleware.js:120]: File an issue on this.

File: src/api/sso/test/e2e/signup-flow.test.js [hunk 19]
```diff
@@ -117,35 +115,28 @@ describe('Signup Flow', () => {
       expect(jwt.family_name).toEqual(galileoGalilei.lastName);
       expect(jwt.name).toEqual(galileoGalilei.displayName);
       expect(jwt.roles).toEqual(['seneca', 'telescope']);
-      expect(jwt.picture).toEqual(galileoGalilei.github.avatarUrl);
+      expect(jwt.picture).toEqual(galileoGalilei.githubAvatarUrl);
 
       return { id: jwt.sub, token };
     }
 
+    // TODO:
```
Comment (humphd) [inline src/api/sso/test/e2e/signup-flow.test.js:123]: Let's delete all this commented code, and @joelazwar can add it back when he writes these tests with the proper JWT authentication for a browser.

File: src/api/sso/test/e2e/signup-flow.test.js [hunk 20]
```diff
@@ -117,35 +115,28 @@ describe('Signup Flow', () => {
...
+    //     const { error } = await supabase.from('telescope_profiles').insert({...});
+    //     expect(error).toBeTruthy();
+    // }
 
     const { accessToken } = await partOne();
     const feedUrls = await partTwo(accessToken);
-    const { id, token } = await partThree(feedUrls, accessToken);
-    await partFour(id, token);
+    await partThree(feedUrls, accessToken);
+    // const { id, token } = await partThree(feedUrls, accessToken);
```
Comment (humphd) [inline src/api/sso/test/e2e/signup-flow.test.js:138]: Delete this too for now, @joelazwar can add it back in new tests.

File: src/api/sso/test/e2e/utils.js [hunk 21]
```diff
@@ -1,6 +1,15 @@
 // Common utility functions and data for the sso tests
 const { decode } = require('jsonwebtoken');
-const { createServiceToken, hash, fetch } = require('@senecacdot/satellite');
+const { hash } = require('@senecacdot/satellite');
+
+const { createClient } = require('@supabase/supabase-js');
+
+const { SERVICE_ROLE_KEY } = process.env;
+
+// Using the an example SERVICE_ROLE_KEY for testing
```
Comment (humphd) [inline src/api/sso/test/e2e/utils.js:9]: This comment needs clarification:

```
// From the browser, we need to access Supabase outside the docker container, so
// we can't use the normal SUPABASE_URL.  We also use the SERVICE_ROLL_KEY for
// admin access, which isn't acceptable outside of testing.
```

**Review by humphd — CHANGES_REQUESTED** [review]
A couple minor things and we can land this.  Amazing work.

File: src/api/sso/src/middleware.js (hunk 18 above)
Comment (humphd) [reply src/api/sso/src/middleware.js:120]: Nice, thank you.

**Review by humphd — APPROVED** [review]
Superb! Spectacular! Stupendous!

Can't wait to get this ready to ship on staging.

r+ with a passing CI run from me.

**Comment by humphd** [comment]
@joelazwar you should review this so we can get it in, and you can build on it.

**Review by TueeNguyen — APPROVED** [review]
I'm gonna run this locally, I've been looking at files only
