### PR TITLE
Fix #875 - harmonize our user profile object for the two SSO implementations we have

### LINKED ISSUE #875: Staging object for SSO needs to match Develop SSO.
**What happened**:
Currently, we have a mock SSO that seneca provided at https://dev.telescope.cdot.systems/
The object currently returned is not set-up with our current frontend.  Creating one single object with the same variable names will allow us to match the development side, so when we finally move
to the official Seneca SSO, our site should work.

**What should have happened**:

**How to reproduce it (as precise as possible)**: 
You can log in using one of the developer accounts that were provided to certain users, and see that it does not show a correct logged-in status.  If you were to change everything to that SSO, the current SSO would not work. 

**Anything else we need to know?**:

**Environment**: All.

- OS: All
- Browser: All

### PR DESCRIPTION
**Pull request by Grommers00**
## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR allows users to login using our docker image that will mimic the object returned from the Seneca SSO object.  You can test this with docker-compose up --build and try logging in
as user1 pw:user1pass

We will also have to test on the development side.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/web/authentication.js [hunk 1]
```diff
@@ -82,8 +82,16 @@ function init(passport) {
 
   // Add session user object de/serialize functions
   passport.serializeUser(function(user, done) {
-    // TODO: is it necessary to use JSON vs. Object?
-    done(null, JSON.stringify(user));
+    const user2 = {
+      name: user['http://schemas.microsoft.com/identity/claims/displayname']
+        ? user['http://schemas.microsoft.com/identity/claims/displayname']
+        : 'Hans Lippershey',
```
Comment (manekenpix) [inline src/backend/web/authentication.js]: Hans Lippershay? :smile:  nice touch!
We could also consider saying `Telescope Developer`.

File: src/backend/web/authentication.js [hunk 2]
```diff
@@ -82,8 +82,16 @@ function init(passport) {
 
   // Add session user object de/serialize functions
   passport.serializeUser(function(user, done) {
-    // TODO: is it necessary to use JSON vs. Object?
-    done(null, JSON.stringify(user));
+    const user2 = {
+      name: user['http://schemas.microsoft.com/identity/claims/displayname']
```
Comment (humphd) [inline src/backend/web/authentication.js]: According to https://github.com/kristophjunge/docker-test-saml-idp#usage, we'll get a `username`, `name`, and `email` from the local php testing IdP, and from Seneca we get `http://schemas.microsoft.com/identity/claims/displayname`.  Let's expect one or the other of these two.  If we don't get one of these, that's an error worth logging vs. using a default.

File: src/backend/web/authentication.js [hunk 3]
```diff
@@ -82,8 +82,16 @@ function init(passport) {
 
   // Add session user object de/serialize functions
   passport.serializeUser(function(user, done) {
-    // TODO: is it necessary to use JSON vs. Object?
-    done(null, JSON.stringify(user));
+    const user2 = {
```
Comment (humphd) [inline src/backend/web/authentication.js]: Instead of creating `user2` do:

```js
done(null, JSON.stringify({
  name: ...,
  email: ...,
});
```

File: simplesamlphp-users.php [hunk 4]
```diff
@@ -0,0 +1,31 @@
+<?php
+
```
Comment (humphd) [inline simplesamlphp-users.php]: Please add a comment here:

```php
/*
  Specify user info for https://hub.docker.com/r/kristophjunge/test-saml-idp/ in the same format
  as our Seneca IdP will give it.  This is modeled on the original config here:
  https://github.com/kristophjunge/docker-test-saml-idp/blob/master/config/simplesamlphp/authsources.php
*/

Comment (humphd) [reply simplesamlphp-users.php]: Why did this get resolved?  There's no comment yet.

Comment (Grommers00) [reply simplesamlphp-users.php]: Oops - forgot to push. Had it commited.

Comment (Grommers00) [reply simplesamlphp-users.php]: Its up now :)

File: src/backend/web/authentication.js [hunk 5]
```diff
@@ -82,8 +82,13 @@ function init(passport) {
...
   // Add session user object de/serialize functions
   passport.serializeUser(function(user, done) {
-    // TODO: is it necessary to use JSON vs. Object?
-    done(null, JSON.stringify(user));
+    done(
+      null,
+      JSON.stringify({
+        name: user['http://schemas.microsoft.com/identity/claims/displayname'],
+        email: user['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'],
+      })
```
Comment (humphd) [inline src/backend/web/authentication.js]: Let's also add `id: user.nameID`, since we'll need that for database purposes.

File: simplesamlphp-users.php [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+            'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress' => 'user1@example.com',
+            'http://schemas.microsoft.com/identity/claims/displayname' => 'Johannes Kepler'
+        ),
+        'user2:user2pass' => array(
+            'uid' => array('2'),
+            'eduPersonAffiliation' => array('group2'),
+            'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress' => 'user2@example.com',
+            'http://schemas.microsoft.com/identity/claims/displayname' => 'Galileo Galilei',
+        ),
+        'LippersheyH:telescope' => array(
```
Comment (humphd) [inline simplesamlphp-users.php]: In a follow-up, we need to document this.  I think I can do it in my other PR, #810.  Remind me.
