### PR TITLE
fix the bug set LOG_LEVEL in .env is not working

### LINKED ISSUE #1264: LOG_LEVEL works via shell but not .env
I noticed today that I couldn't set my `LOG_LEVEL` via the `.env`, but could on the command line.

In both cases I used `LOG_LEVEL=debug` but got `INFO` vs. `DEBUG` when I did it via `.env`, whereas this worked on macOS:

```sh
$ LOG_LEVEL=debug npm start
```

### PR DESCRIPTION
**Pull request by tianlangwu**
## Issue This PR Addresses
fix #1264 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Fix the bug that the setting of LOG_LEVEL in .env is not working properly. Even set `LOG_LEVEL=debug`, `npm start` still print as `LOG_LEVEL=info`. 

Remove `logger` dependency and replaced it to `Console.log()/error()` inside `lib/config.js`.

To test this, you can set `LOG_LEVEL=debug` in the .env, then run the server `npm start`.

```sh
[ 2020-11-04 17:55:58.805 ] INFO  (16544 on LAPTOP-LCOUFEIF): Loading all feeds into feed queue for processing
[ 2020-11-04 17:55:58.810 ] INFO  (16544 on LAPTOP-LCOUFEIF): Telescope listening on port 3000
[ 2020-11-04 17:55:59.335 ] INFO  (16544 on LAPTOP-LCOUFEIF): Connected to elasticsearch!
[ 2020-11-04 17:55:59.336 ] INFO  (16544 on LAPTOP-LCOUFEIF): Starting 1 instance of feed processor.
[ 2020-11-04 17:55:59.354 ] DEBUG (16544 on LAPTOP-LCOUFEIF): Job 0f20520bfe is active
[ 2020-11-04 17:56:00.692 ] INFO  (2132 on LAPTOP-LCOUFEIF): [HTTP 304 - Not Modified] Feed not downloaded: http://shavedyak.blogspot.com/feeds/posts/default/-/opensource
[ 2020-11-04 17:56:00.697 ] DEBUG (16544 on LAPTOP-LCOUFEIF): Job 0f20520bfe completed.
[ 2020-11-04 17:56:00.706 ] DEBUG (16544 on LAPTOP-LCOUFEIF): Job bb9952ec17 is active
```

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/utils/logger.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ const expressPino = require('express-pino-logger');
 const os = require('os');
 const path = require('path');
 
-require('../lib/config');
+require('dotenv').config();
```
Comment (humphd) [inline src/backend/utils/logger.js:6]: We do this in [lib/config.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/lib/config.js) already, as well as some fallback logic.

I'd like to isolate the config loading to `lib/config.js` vs. doing it here.  Can you see what we're doing wrong in that file instead of this change?

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/backend/utils/logger.js (hunk 1 above)
Comment (tianlangwu) [reply src/backend/utils/logger.js:6]: Yea, I am going to look it

Comment (tianlangwu) [reply src/backend/utils/logger.js]: In config.js file. It works as long as` const result = dotenv.config(); ` before `const { logger } = require('../utils/logger');`

Comment (humphd) [reply src/backend/utils/logger.js]: Ah, interesting, because we have a circular dependency here.

Let's rip the `logger` dependency out of `lib/config.js` and use `console.log()` in that file instead.  Maybe we can avoid logging in there altogether.

File: src/backend/lib/config.js [hunk 2]
```diff
@@ -1,11 +1,10 @@
 const path = require('path');
 const dotenv = require('dotenv');
-const { logger } = require('../utils/logger');
 
 const result = dotenv.config();
 
-if (result.error && logger) {
-  logger.error(
+if (result.error) {
+  console.error(
```
Comment (humphd) [inline src/backend/lib/config.js:7]: `console.warn` vs. `console.error` here please, so we don't include a stack

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/backend/lib/config.js (hunk 2 above)
Comment (tianlangwu) [reply src/backend/lib/config.js:7]: thanks for the advice!

**Review by humphd — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]
Tested locally :+1:
