### PR TITLE
Fixes #1104 fix error in building the frontend

### LINKED ISSUE #1104: Error building the front-end
**What happened**:

Merging #1103 broke the frontend. During the building process, this happened:

```sh
success open and validate gatsby-configs - 0.054s
success load plugins - 0.828s
success onPreInit - 18.606s
success delete html and css files from previous builds - 0.021s
success initialize cache - 0.010s
success copy gatsby files - 0.037s
success onPreBootstrap - 0.005s
success createSchemaCustomization - 0.009s
success source and transform nodes - 1.774s
success building schema - 0.370s

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Reducers may not dispatch actions.



  Error: Reducers may not dispatch actions.
  
  - redux.js:214 dispatch
    [frontend]/[redux]/lib/redux.js:214:13
  
  - index.js:64 action
    [frontend]/[gatsby]/dist/redux/index.js:64:88
  
  - index.js:14 Object.dispatch
    [frontend]/[redux-thunk]/lib/index.js:14:16
  
  - index.js:45 dispatch
    [frontend]/[gatsby]/[gatsby-cli]/lib/reporter/redux/index.js:45:9
  
  - redux.js:483 Object.createLog
    [frontend]/[redux]/lib/redux.js:483:12
  
  - reporter.js:168 Reporter.warn.text [as warn]
    [frontend]/[gatsby]/[gatsby-cli]/lib/reporter/reporter.js:168:41
  
  - patch-console.js:22 Console.console.warn.args [as warn]
    [frontend]/[gatsby]/[gatsby-cli]/lib/reporter/patch-console.js:22:14
  
  - utils.js:449 Object.warn
    [frontend]/[xstate]/lib/utils.js:449:26
  
  - StateNode.js:1313 
    [frontend]/[xstate]/lib/StateNode.js:1313:29
  
  - Array.map
  
  - StateNode.js:1311 StateNode.formatTransitions
    [frontend]/[xstate]/lib/StateNode.js:1311:18
  
  - StateNode.js:321 StateNode.get [as transitions]
    [frontend]/[xstate]/lib/StateNode.js:321:51
  
  - StateNode.js:296 StateNode.get [as on]
    [frontend]/[xstate]/lib/StateNode.js:296:36
  
  - StateNode.js:230 
    [frontend]/[xstate]/lib/StateNode.js:230:93
  
  - Array.forEach
  
  - StateNode.js:230 StateNode._init
    [frontend]/[xstate]/lib/StateNode.js:230:45
  

failed createPages - 0.088s
```

I don't think it's directly related to the changes made in #1103 (I'd say it's gatsby).
Check [this](https://github.com/gatsbyjs/gatsby/issues/20082) for possible solutions.

**What should have happened**:
Telescope should've been able to run after the merge.

**How to reproduce it (as precise as possible)**:
Try to run Telescope using the latest commit.

**Anything else we need to know?**:
**Important**
Currently, Telescope uses `gatsby 2.20.23`. Switching to latest (`2.24.2`) seems to *fix* the problem, but it creates a different one (that might be related to telescope, not gatsby).
Trying to run Telescope using `gatsby v2.24.2` generates this message:
```sh
success open and validate gatsby-configs - 0.073s
success load plugins - 0.766s
success onPreInit - 13.889s
success delete html and css files from previous builds - 0.021s
success initialize cache - 0.008s
success copy gatsby files - 0.030s
success onPreBootstrap - 0.008s
success createSchemaCustomization - 0.018s
success source and transform nodes - 1.862s
success building schema - 0.381s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot read property 'map' of undefined

File: gatsby-node.js:94:18

not finished createPages - 0.035s

```

**Environment**:

- OS:
- Browser:

### PR DESCRIPTION
**Pull request by cindyledev**
## Issue This PR Addresses
Closes #1104 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

update gatsby package and fix graphql error in gatsby-node.js

Gatsby changed the way they do createPages for Markdown pages so this PR updates related files with slugs. Hopefully this fix works in dev and it wasn't just my machine.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/gatsby-node.js [hunk 1]
```diff
@@ -89,15 +89,15 @@ exports.onPreInit = async function ({ reporter }) {
 exports.createPages = async ({ actions, graphql, reporter }) => {
   const { createPage } = actions;
 
-  const pageTemplate = path.resolve(`src/templates/template.js`);
+  const pageTemplate = require.resolve(`./src/templates/template.js`);
```
Comment (humphd) [inline src/frontend/gatsby-node.js:92]: First time I've seen `require.resolve()`, TIL!
