### PR TITLE
[next] Fixes issue-1541: Ported AuthorSearchInput component to Next.JS

### LINKED ISSUE #1541: [next] Port AuthorSearchInput to NextJS
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/SearchInput/AuthorSearchInput.jsx
**What would you like to be added**:
Port AuthorSearchInput component to NextJS using TS
**Why would you like this to be added**:
Porting reason

### PR DESCRIPTION
**Pull request by chrispinkney**
## Issue This PR Addresses
Fixes #1541

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI
- [x] **Next.JS Port**

## Description
This PR ports over the `AuthorSearchInput` component to Next.JS.

**_However I have a few concerns I'd like to run by everyone before we merge this:_**

- I'm currently getting an ESLint error: `A control must be associated with a text label.eslint(jsx-a11y/control-has-associated-label)` when I remove `/* eslint-disable jsx-a11y/control-has-associated-label */` from the top of the file.
  - FYI: The original Gatsby version of this component also disabled this rule.
  - I've never heard of `<datalist>` before so upon a quick google it seems like we're doing everything right, as `<input>` has a list of `search-suggestions` which matches the `<datalist>`'s `id`, but ESLint is still screaming. 
  - If the input is enclosed by the `datalist` tag, the error goes away (but it doesn't look like this is the correct way of using `datalist`.

Let me know if you guys have any suggestions on this as restricting ESLint makes angels cry, though this case might be an exception.

PS: I added a todo comment for when the parent component `SearchInput` gets implemented. The style used in both `AuthorSearchInput` and `PostSearchInput` can be moved to the parent component.

## How to test:
In `index.tsx`:
- `import AuthorSearchInput from '../components/SearchInput/AuthorSearchInput';`
- `<AuthorSearchInput text="Search Me!" />`

Which should yield:
firefox_2021-01-20_15-31-53

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+import { makeStyles } from '@material-ui/core/styles';
+
+type AuthorSearchInputProps = {
+  text: string;
+  onChange: (e: ChangeEvent<HTMLInputElement>) => void;
+};
+
+// TODO: when SearchInput is ported to next js this style
+// (also found in PostSearchInput.tsx) can be adequately ported as well
+// i.e. by moving the below style to the SearchInput component
```
Comment (manekenpix) [inline src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx:12]: I think it'd be better to have this comment in the affected issues instead of here so we won't have to hope that the people implementing the other components see this.

Comment (chrispinkney) [reply src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx]: Sounds good to me, I'll remove it and place it in the appropriate issue. Thanks Josue!

File: src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+      <input
+        className={classes.input}
+        list="search-suggestions"
+        placeholder="How to Get Started in Open Source"
+        aria-label="search telescope"
+        value={text}
+        onChange={onChange}
+      />
+
+      <datalist id="search-suggestions" />
```
Comment (manekenpix) [inline src/frontend/next/src/components/SearchInput/AuthorSearchInput.tsx:49]: Adding an `aria-label` to `datalist` seems to fix the eslint problem.

**Review by manekenpix — CHANGES_REQUESTED** [review]

**Review by manekenpix — APPROVED** [review]
LGTM :+1: 

image

**Review by humphd — APPROVED** [review]

**Review by HyperTHD — APPROVED** [review]
