### PR TITLE
Issue #1410 Changed function name to LoadAutoScroll

### LINKED ISSUE #1410: Wrong function name in `src/frontend/src/components/Posts/LoadAutoScroll.jsx`
**What happened**:

In the /LoadAutoScroll.jsx, the function name is `LoadMoreButton` which is the previous function for rendering more posts #1229.  This should change to `LoadAutoScroll()`
```
function LoadMoreButton({ onScroll }) {  // should be LoadAutoScroll
  const classes = useStyles();
  const $buttonRef = useRef(null);
...
```

**What should have happened**:

`LoadMoreButton` ---> `LoadAutoScroll`

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:
It seems like I made the mistake in my PR #1229, so I can handle this issue!
**Environment**:

- OS: Window
- Browser: Chrome

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes #1410 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Changed the function name from LoadMoreButton to LoadAutoScroll
Changed onScroll to onClick

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by klee214 — APPROVED** [review]

**Comment by strawberries73** [comment]
@klee214  I noticed that there is an error at onScroll on line 16.  Would you like me to add it to props validation and start the PR again?  
image

**Review by klee214 — CHANGES_REQUESTED** [review]
Sorry I didn't notice that please change the Line 55 `OnClick` -----> `OnScroll`.

File: src/frontend/src/components/Posts/LoadAutoScroll.jsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ const useStyles = makeStyles((theme) => ({
   },
 }));
 
-function LoadMoreButton({ onScroll }) {
+function LoadAutoScroll({ onClick }) {
```
Comment (humphd) [inline src/frontend/src/components/Posts/LoadAutoScroll.jsx:16]: Other way around, this prop needs to be `onScroll` and below on the propTypes you need `onScroll` too.  You can see how it's called at https://github.com/Seneca-CDOT/telescope/blob/e98765297b55125d509166fe97a74eaa751cf3fd/src/frontend/src/components/Posts/Timeline.jsx#L48, which is sending an `onScroll` function.

**Review by humphd — CHANGES_REQUESTED** [review]

**Review by humphd — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]
