### PR TITLE
Fixes #122: add logging to inform user of Redis connection failure

### LINKED ISSUE #122: Catch testing error and display a more user friendly error message.
Currently when running `npm test` you get this error if the Redis server is off:
```
(node:46320) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:46320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:46320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Should catch this error and display a more user friendly error message. 

Here is a link that may help facebook/jest#5311
- - -
I think this issue was mention before, but I couldn't find the issue relating to this one. Can close if it already exist.

### PR DESCRIPTION
**Pull request by Silvyre**
## Issue This PR Addresses

Fixes #122

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

As suggested in https://github.com/Seneca-CDOT/telescope/issues/48#issuecomment-550079621, added logic to handle 'ECONNREFUSED' errors within the Bull queue: 'ECONNREFUSED' are now logged an informative blurb instead of a stack trace.

https://github.com/Silvyre/telescope/blob/818ba4c9404f2cd5f2a70b7826a3650f1c215587/src/backend/lib/queue.js#L32-L43

Redis error

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/lib/queue.js [hunk 1]
```diff
@@ -31,7 +31,15 @@ function createQueue(name) {
   })
     .on('error', err => {
       // An error occurred
-      logger.error({ err }, `Queue ${name} error`);
+      if (err.code === 'ECONNREFUSED') {
+        logger.info(
```
Comment (humphd) [inline src/backend/lib/queue.js]: Probably this should still remain an error: `logger.error` vs. `logger.info`

File: src/backend/lib/queue.js [hunk 2]
```diff
@@ -31,7 +31,15 @@ function createQueue(name) {
...
+          '\n\n\t💡  It appears that Redis is not running on your machine.',
```
Comment (humphd) [inline src/backend/lib/queue.js]: Love the light bulb!  Great idea.

**Comment by humphd** [comment]
@yatsenko-julia I flagged you for review on this as well.  Since you recently hit this issue yourself, could you try pulling @Silvyre's PR and testing it with your setup to see if you get the message?

File: src/backend/lib/queue.js (hunk 2 above)
Comment (Silvyre) [reply src/backend/lib/queue.js]: Thanks!

File: src/backend/lib/queue.js (hunk 1 above)
Comment (Silvyre) [reply src/backend/lib/queue.js]: Sure, change made: https://github.com/Seneca-CDOT/telescope/pull/553/commits/ffcebe5070a824d3942778229e4dc60d2f2b55e6

**Comment by humphd** [comment]
I also tested this locally, and here is what I see, with Redis disabled on my Mac:

```
$ npm start

> telescope@0.0.1 start /Users/humphd/repos/telescope
> node src/backend

express-session deprecated req.secret; provide secret option src/backend/web/routes/login.js:17:12
[ 2020-01-19 17:14:20.536 ] INFO  (39125 on brightness.local): Telescope listening on port 3000
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
[ 2020-01-19 17:14:20.605 ] ERROR (39125 on brightness.local):

	💡  It appears that Redis is not running on your machine.
	   Please see our documentation for how to install and run Redis:
	   https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md

[ 2020-01-19 17:14:20.606 ] ERROR (39125 on brightness.local): Queue feed-queue error
    err: {
      "type": "Error",
      "message": "Error initializing Lua scripts",
      "stack":
          Error: Error initializing Lua scripts
              at /Users/humphd/repos/telescope/node_modules/bull/lib/queue.js:155:30
              at processTicksAndRejections (internal/process/task_queues.js:93:5)
    }
[ 2020-01-19 17:14:20.608 ] ERROR (39125 on brightness.local):

	💡  It appears that Redis is not running on your machine.
	   Please see our documentation for how to install and run Redis:
	   https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md

[ 2020-01-19 17:14:20.619 ] INFO  (39125 on brightness.local): Received UNHANDLED REJECTION, starting shut down
[ 2020-01-19 17:14:20.619 ] ERROR (39125 on brightness.local):
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED 127.0.0.1:6379",
      "stack":
          Error: connect ECONNREFUSED 127.0.0.1:6379
              at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
      "errno": "ECONNREFUSED",
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "127.0.0.1",
      "port": 6379
    }
[ 2020-01-19 17:14:20.621 ] INFO  (39125 on brightness.local): Web server shut down.
[ 2020-01-19 17:14:20.621 ] INFO  (39125 on brightness.local): Feed queue shut down.
[ 2020-01-19 17:14:20.621 ] INFO  (39125 on brightness.local): Completing shut down.
```

@Silvyre, your message happens multiple times.  Do you think it might be possible to get this to only happen once?  If it scrolls off the screen, it loses some of its value.

**Comment by Silvyre** [comment]
> 
> @Silvyre, your message happens multiple times. Do you think it might be possible to get this to only happen once? If it scrolls off the screen, it loses some of its value.

Looking into this!

**Comment by Silvyre** [comment]
> 
> 
> > @Silvyre, your message happens multiple times. Do you think it might be possible to get this to only happen once? If it scrolls off the screen, it loses some of its value.
> 
> Looking into this!

How's this? I added a simple check to ensure the message is logged only once: https://github.com/Seneca-CDOT/telescope/pull/553/commits/1a6c56e9a31983386ace77158eaa833f3e58be6a

File: src/backend/lib/queue.js [hunk 3]
```diff
@@ -9,6 +9,7 @@ const { logger } = require('../utils/logger');
 
 const client = createRedisClient();
 const subscriber = createRedisClient();
+let redisErrorLogged = false;
```
Comment (humphd) [inline src/backend/lib/queue.js]: This is named in a very general way, can we do better?  You're keeping track of whether or not we've given a hint about installing Redis if it's not running.  What about `redisNotAvailableLogged`?  Or something that makes sense to you.  I'd also throw a comment above this line explaining its intent.

**Comment by yatsenko-julia** [comment]
I am not sure why but I've got a different message. Here it is: 

```
$ npm start

> telescope@0.0.1 start /Users/julia-yatsenko/Downloads/telescope-master
> node src/backend

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'dotenv'
Require stack:
- /Users/julia-yatsenko/Downloads/telescope-master/src/backend/lib/config.js
- /Users/julia-yatsenko/Downloads/telescope-master/src/backend/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/julia-yatsenko/Downloads/telescope-master/src/backend/lib/config.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/julia-yatsenko/Downloads/telescope-master/src/backend/lib/config.js',
    '/Users/julia-yatsenko/Downloads/telescope-master/src/backend/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telescope@0.0.1 start: `node src/backend`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telescope@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

**Comment by humphd** [comment]
@yatsenko-julia that likely means `npm install` hasn't been run, or hasn't completed successfully.  Try this:

```
rm -fr node_modules
npm install
npm start
```

**Comment by yatsenko-julia** [comment]
@humphd Thank you! Now it works.

File: src/backend/lib/queue.js [hunk 4]
```diff
@@ -31,7 +32,18 @@ function createQueue(name) {
   })
     .on('error', err => {
       // An error occurred
-      logger.error({ err }, `Queue ${name} error`);
+      if (err.code === 'ECONNREFUSED') {
+        if (!redisErrorLogged) {
```
[the remark this answers is not in the document]
Comment (Silvyre) [reply src/backend/lib/queue.js]: Agreed, and done: https://github.com/Seneca-CDOT/telescope/pull/553/commits/16b6007a26cab43eccff2a602ce8958282a47213

File: src/backend/lib/queue.js (hunk 3 above)
Comment (Silvyre) [reply src/backend/lib/queue.js]: Sure, and done (I settled on `redisConnectionRefusalLogged`): https://github.com/Seneca-CDOT/telescope/pull/553/commits/16b6007a26cab43eccff2a602ce8958282a47213
