### PR TITLE
Fixes-2618: Refactor search routes

### LINKED ISSUE #2618: Refactor the search to use the advanced search route
**What would you like to be added**:
[The advanced search route backend is being implemented](https://github.com/Seneca-CDOT/telescope/pull/2617). However the react context written for the search needs to be refactored to change the route we push. Right now it's very static and not too flexible.  

**Why would you like this to be added**:
Refactor all of the search queries to use the one query we have. the new advancedsearch is quite flexible in what we can search for posts.

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
Fixes #2618 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
In https://github.com/Seneca-CDOT/telescope/pull/2617 we added an advanced route. The advanced route is more flexible for search terms and capabilities. In this PR I changed the route used in the search results so that we use the new "advanced" route. In another PR I will clean up the regular search as we are now leveraging the more advanced route - and will be the main route meaning no more `/advanced` it will be `/`

## Steps to test the PR
- `cp config/env.development .env`
- `docker-compose --env-file ./config/env.development up --build search elasticsearch redis posts nginx planet`

1. Go to search and select author search an author - look in the network tab for dev tools, you will see the results coming from the new route.
2. Do the same with posts.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/web/src/components/SearchResults.tsx [hunk 1]
```diff
@@ -59,7 +59,9 @@ const SearchResults = () => {
   const [totalPosts, setTotalPosts] = useState(0);
 
   const prepareUrl = (index: number) =>
-    `${searchServiceUrl}?text=${encodeURIComponent(textParam)}&filter=${filter}&page=${index}`;
+    `${searchServiceUrl}?${filter === 'author' ? `author` : `post`}=${encodeURIComponent(
```
Comment (HyperTHD) [inline src/web/src/components/SearchResults.tsx:62]: I haven't tested this yet, but you could apply the logic for the filter in the Provider and just import it through the search hook, rather than doing this

**Review by HyperTHD — CHANGES_REQUESTED** [review]
Looks nice, just a few things aside from updating the search tests as well so this passes CI

File: src/web/src/components/SearchResults.tsx (hunk 1 above)
Comment (AmasiaNalbandian) [reply src/web/src/components/SearchResults.tsx:62]: I rather not change it, because in the upcoming PRs for the advanced route, I'm converting it to something like:
```
${searchServiceUrl}/?author=${encodeURIComponent(author)}&post=${encodeURIComponent(
      post
    )}&title=${encodeURIComponent(title)}${from ? `&from=${from}` : ''}${to ? `&to=${to}` : ''}`;
```

We're completely removing out the filter. We can search stuff with empty fields so it's no longer this or that. It's a lot more flexibility.

File: src/api/search/src/routes/query.js [hunk 2]
```diff
@@ -1,22 +1,12 @@
 const { Router, createError } = require('@senecacdot/satellite');
 const { validateQuery } = require('../bin/validation');
-const { search, advancedSearch } = require('../search');
+const { search } = require('../search');
 
 const router = Router();
 
 router.get('/', validateQuery, async (req, res, next) => {
   try {
-    const { text, filter, page, perPage } = req.query;
```
Comment (AmasiaNalbandian) [inline src/api/search/src/routes/query.js:9]: This is the MAIN part of the PR - removed the regular search to use the advanced route only(much more flexible and also covers all cases with the current search). I then cleaned up all the code from the regular search. So now there is no more `/advanced` ----> that route is now the main path `/`

**Comment by AmasiaNalbandian** [comment]
> You'll need to update the routes in tests as well to pass the unit tests

Sorry about removing you and Jia's beautiful code <3

**Comment by tpmai22** [comment]
@rclee91 @HyperTHD @aserputov Let's jump on this

**Review by rclee91 — COMMENTED** [review]
I am not that familiar with front end
but tested locally and the search bar works in `dev` mode
Will approve on rebase

**Comment by AmasiaNalbandian** [comment]
> I am not that familiar with front end but tested locally and the search bar works in `dev` mode Will approve on rebase

That's all the PR really is - Just use the advanced route to make it the default route, and then query using that route, which supports same functionality. You can test by going to searchbar in front end, then checking the network tab to see the request is no longer
    `?text=sometext&filter=author&page=0;`
 but instead it is 
    `author=sometext&page=0`

**Review by DukeManh — APPROVED** [review]

**Review by rclee91 — APPROVED** [review]

**Comment by tpmai22** [comment]
@AmasiaNalbandian I guess we all learn having small PRs might be the move ! Thank you for your hard work here

**Review by tpmai22 — APPROVED** [review]
