### PR TITLE
Fixes #624: delay feed processing in response to rate limitation

### LINKED ISSUE #624: Deal with 429 responses from medium.com, and other feeds
**What happened**:

I noticed that [Tim's blog feed](https://medium.com/feed/@timfosteman) is showing on our 
old planet, but not on Telescope.  I took a look through the logs:

```
[ 2020-01-28 21:02:49.116 ] INFO  (80376 on brightness.local): [HTTP 429 - Too Many Requests] Feed not downloaded: https://medium.com/feed/@timfosteman
```

Most likely we're being rate limited, and it would be good to try and get the `Retry-After` value (if sent) so we can hold off before we attempt to request it again.

**What should have happened**:

We're probably hitting the site too often, and need to slow down our update rate

**How to reproduce it (as precise as possible)**:

I was able to reproduce this manually by running this curl command a bunch of times:

```
curl -I https://medium.com/feed/@timfosteman
HTTP/2 429
date: Wed, 29 Jan 2020 02:15:06 GMT
content-type: application/octet-stream
content-length: 59
set-cookie: __cfduid=d71f3769d4fd81234fc3a8896ffdc46791580264106; expires=Fri, 28-Feb-20 02:15:06 GMT; path=/; domain=.medium.com; HttpOnly; SameSite=Lax
cf-cache-status: DYNAMIC
set-cookie: uid=lo_Am9JI3p26hzR; Expires=Thu, 28-Jan-21 02:15:06 GMT; Domain=.medium.com; Path=/; Secure; HttpOnly
set-cookie: __cfruid=764ce017648591f95313a363a58144e49c585a94-1580264106; path=/; domain=.medium.com; HttpOnly; Secure; SameSite=None
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
alt-svc: h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 55c7b249591af981-YYZ

Too many feed requests. See: https://medium.superfeedr.com
```

It doesn't give a `Retry-After`, and if I wait a few minutes it starts working again.  I can't find good docs on how long to wait, but I wonder if we should just wait for 1 hour when we hit this for a feed.

### PR DESCRIPTION
**Pull request by Silvyre**
## Issue This PR Addresses

Fixes #624 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Implements and tests functionality that temporarily delays further processing of feeds after a failed processing attempt that resulted in an HTTP 429 (Too Many Requests) response.

The current implementation delays feed processing by ~15 seconds~ [an hour](https://github.com/Seneca-CDOT/telescope/pull/726#discussion_r379869189) in such a case.

_Thank you very much, @humphd, for your assistance in tackling this issue!_

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/data/feed.js [hunk 1]
```diff
@@ -44,6 +51,21 @@ class Feed {
     return isInvalid(this.id);
   }
 
+  /**
+   * Flags a feed in the database, indicating that its processing should be delayed
+   * @param {Number} seconds - duration in seconds for which processing should wait
+   */
```
Comment (humphd) [inline src/backend/data/feed.js]: Add another line to this comment:

```js
* Returns a Promise
```

File: src/backend/data/feed.js [hunk 2]
```diff
@@ -44,6 +51,21 @@ class Feed {
...
+  setDelayed(seconds) {
+    setDelayedFeed(this.id, seconds);
+  }
+
+  /**
+   * Checks whether the current feed is delayed or not
+   */
```
Comment (humphd) [inline src/backend/data/feed.js]: Add one more line to this comment:

```js
* Returns a Promise<Boolean>
```

File: src/backend/feed/processor.js [hunk 3]
```diff
@@ -141,7 +141,8 @@ module.exports = async function processor(job) {
           logger.warn(`${info.status} Feed no longer available: ${feed.url}`);
           break;
         case 429:
-          logger.warn(`${info.status} Feed requested too many times: ${feed.url}`);
+          logger.warn(`${info.status} Feed requested too many times, setting delay: ${feed.url}`);
+          feed.setDelayed(15);
```
Comment (humphd) [inline src/backend/feed/processor.js]: Let's make this configurable in the env, and default to 60 seconds * 60 minutes = 1 hour (3600s)

File: src/backend/utils/storage.js [hunk 4]
```diff
@@ -58,6 +61,13 @@ module.exports = {
 
   isInvalid: id => redis.exists(createInvalidFeedKey(id)),
 
+  setDelayedFeed: (id, seconds) => {
+    const key = createDelayedFeedKey(id);
+    redis.set(key, seconds, 1);
```
Comment (humphd) [inline src/backend/utils/storage.js]: I think we need a `return` here (line 66), and also in the `setInvalidFeed` above.  We need to return the Promise that this will give us.

File: src/backend/data/feed.js (hunk 1 above)
Comment (Silvyre) [reply src/backend/data/feed.js]: Sure, fixed in https://github.com/Seneca-CDOT/telescope/pull/726/commits/850b45fd82e7ffcf6bcc1c91ecc3b4b9e7efd949

File: src/backend/data/feed.js (hunk 2 above)
Comment (Silvyre) [reply src/backend/data/feed.js]: Done: https://github.com/Seneca-CDOT/telescope/pull/726/commits/850b45fd82e7ffcf6bcc1c91ecc3b4b9e7efd949

File: src/backend/feed/processor.js (hunk 3 above)
Comment (Silvyre) [reply src/backend/feed/processor.js]: Sure, added a `FEED_PROCESSING_DELAY_SEC` variable to `env.example`: https://github.com/Seneca-CDOT/telescope/pull/726/commits/850b45fd82e7ffcf6bcc1c91ecc3b4b9e7efd949

File: src/backend/utils/storage.js (hunk 4 above)
Comment (Silvyre) [reply src/backend/utils/storage.js]: Done: https://github.com/Seneca-CDOT/telescope/pull/726/commits/850b45fd82e7ffcf6bcc1c91ecc3b4b9e7efd949

File: src/backend/feed/processor.js [hunk 5]
```diff
@@ -147,7 +147,8 @@ module.exports = async function processor(job) {
           logger.warn(`${info.status} Feed no longer available: ${feed.url}`);
           break;
         case 429:
-          logger.warn(`${info.status} Feed requested too many times: ${feed.url}`);
+          logger.warn(`${info.status} Feed requested too many times, setting delay: ${feed.url}`);
+          feed.setDelayed(process.env.FEED_PROCESSING_DELAY_SEC || 3600);
```
Comment (humphd) [inline src/backend/feed/processor.js]: This returns a Promise, since it talks to Redis.  You need to `await feed.setDelayed...`

File: test/feed.test.js [hunk 6]
```diff
@@ -76,5 +76,12 @@ describe('Fost data class tests', () => {
       expect(persisted.lastModified).toEqual('lastModified');
       expect(persisted.etag).toBe(null);
     });
+
+    test('Feed.isDelayed() should return truthy only after Feed.setDelayed()', async () => {
+      const feed = await Feed.byUrl(data.url);
+      expect(await feed.isDelayed()).toBeFalsy();
```
Comment (humphd) [inline test/feed.test.js]: Does this not return a pure Boolean?  Can you not use `toBe(false)` and `toBe(true)` below?  If not, we should fix that.

File: src/backend/feed/processor.js (hunk 5 above)
Comment (Silvyre) [reply src/backend/feed/processor.js]: Done: https://github.com/Seneca-CDOT/telescope/pull/726/commits/ab0ec50816580a3a5e72c4cb48c9d55afe6b0cfa

File: test/feed.test.js (hunk 6 above)
Comment (Silvyre) [reply test/feed.test.js]: Fixed in https://github.com/Seneca-CDOT/telescope/pull/726/commits/ab0ec50816580a3a5e72c4cb48c9d55afe6b0cfa

File: src/backend/utils/storage.js [hunk 7]
```diff
@@ -53,11 +56,19 @@ module.exports = {
...
-    redis.set(key, reason);
+    return redis.set(key, reason);
   },
 
   isInvalid: id => redis.exists(createInvalidFeedKey(id)),
 
+  setDelayedFeed: async (id, seconds) => {
+    const key = createDelayedFeedKey(id);
+    const msg = await redis.set(key, seconds, 1);
+    return msg === 'OK';
```
Comment (humphd) [inline src/backend/utils/storage.js]: I don't think we care about this one, let's just return the promise and let it fail that way.

```js
setDelayedFeed: (id, seconds) => redis.set(createDelayedFeedKey(id), seconds, 1);
```

Comment (Silvyre) [reply src/backend/utils/storage.js]: Done! https://github.com/Seneca-CDOT/telescope/pull/726/commits/7f528072e0d5b62e30c4dc0ec9e3b7fd7f35afbf
