### PR TITLE
Fix issue 1464:  Scroll To Top button on the search page does not work on mobile version

### LINKED ISSUE #1464: Scroll To Top button on the search page does not work in mobile version
**What happened**:
Scroll To Top button on the search page does not work for the mobile version.
**What should have happened**:
Scroll To Top button should move the scroll to the top of the page in the mobile version.
**How to reproduce it (as precise as possible)**:
1. Open telescopes in mobile version, click on the search icon to navigate to the search page.
2. Scroll the page down until the button shows, click the button, and nothing happens.

ezgif-2-f24759f3e931

### PR DESCRIPTION
**Pull request by tianlangwu**
## Issue This PR Addresses
Fix #1464 

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Scroll To Top button on the search page now work properly on mobile version. 
To check this, Open telescopes in mobile version, click on the search icon to navigate to the search page.
Scroll the page down until the button shows, and then click the button.

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM

File: src/frontend/gatsby/src/components/SearchPage/SearchPage.jsx [hunk 1]
```diff
@@ -37,6 +41,7 @@ const SearchPage = () => {
   return (
     <div>
       <div className={classes.anchor} id="back-to-top-anchor" />
+      <div className={classes.anchorMobile} id="back-to-top-anchor-mobile" />
```
Comment (humphd) [inline src/frontend/gatsby/src/components/SearchPage/SearchPage.jsx:44]: Why not put this class name on the previous element vs. adding a second one (e.g., have a div with two classes)?  @PedroFonsecaDEV any reason that wouldn't work?

Comment (tianlangwu) [reply src/frontend/gatsby/src/components/SearchPage/SearchPage.jsx:44]: The className just for the different position, I move scroll to the search bar in the mobile version instead of the very top in the desktop version. 
The reason why I put two divs here is that we need two different ids. one div can not have two different ids. I check the banner component. It has two different ids in two different div/grid too.
Screenshot 2020-11-27 121322

**Review by humphd — APPROVED** [review]

File: src/frontend/gatsby/src/components/SearchPage/SearchPage.jsx (hunk 1 above)
Comment (tianlangwu) [reply src/frontend/gatsby/src/components/SearchPage/SearchPage.jsx:44]: I can redesign it to get rid of the extra div. We can only use one .querySelector('#back-to-top-anchor') for both mobile and desktop in ScrollAction.
image
and then add responsive CSS in each component instead of using two querySelectors. It will remove 1 div in Search page and 1 div in Banner.

Do you think is it necessary? Can I make a issue to redesign the querySelector? @humphd
