### PR TITLE
Fixed logging format

### LINKED ISSUE #1448: Logging no longer formatted for pretty display locally
We used to have really nice logging, pretty-printed for local debugging, but now I get raw JSON:

```
{"level":30,"time":1606175748870,"pid":88703,"hostname":"brightness.local","msg":"Starting 1 instance of feed processor."}
```

It might be something about how me `.env` is setup after the Kibana change?  Not sure, but I miss my pretty logs.

cc @c3ho

### PR DESCRIPTION
**Pull request by c3ho**
## Issue This PR Addresses
Fixes #1448 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Now when logging to console, the log messages will look pretty again.

Could someone also test the pino-elastic logging as well for this and make sure it is also working? I tested it, but it was inconclusive for me.

Steps to test fix:
1. in the `.env` file set `LOG_LEVEL` to `info`
1. `docker-compose up redis elasticsearch`
1. `npm start`

Check info messages in terminal tab. They should look pretty now (just like before)

To regression test:
1. in the `.env` file set `LOG_LEVEL` to `info` and set `LOG_ELASTIC` to 1
1. `docker-compose up redis elasticsearch`
1. `npm start`, there should be no logging appearing in terminal tab anymore as they're directed to elasticsearch now
1. navigate to `http://localhost:9200/_cat/indices?v` You should see two rows and under the `indexes` column there should be 2 indexes  `logs` and `posts`
1. Remember to set `LOG_ELASTIC` to blank again in your `.env` file after testing.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/backend/utils/logger.js [hunk 1]
```diff
@@ -39,14 +39,14 @@ const streamToElastic = pinoElastic({
   // Consistency of the write, valid values: 'one', 'quorum', 'all'
   consistency: (process.env.CONSISTENCY || 'one').toLowerCase(),
   // URL of Elasticsearch
-  node: `http://${process.env.ELASTIC_URL}:${process.env.ELASTIC_PORT}`,
+  node: `${process.env.ELASTIC_URL}:${process.env.ELASTIC_PORT}`,
```
Comment (humphd) [inline src/backend/utils/logger.js:42]: We probably need the same treatment that @zg3d is doing in #1443 to build a proper URL + port without duplication of port.  Once that land, you can rebase and use his function.

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/backend/utils/logger.js (hunk 1 above)
Comment (c3ho) [reply src/backend/utils/logger.js]: Newest commit should address these

**Review by humphd — DISMISSED** [review]
Looks good.

**Review by manekenpix — APPROVED** [review]

**Comment by c3ho** [comment]
@humphd Is it safe to assume we have should have an almost even amount of docs in `logs` and `posts` index generated when we use `LOG_LEVEL=info`?

I'm thinking a doc should be created for each feed that we process(or skip)

**Comment by humphd** [comment]
@c3ho sorry, I don't follow what you're asking.  Also, do you want to merge this?

**Comment by c3ho** [comment]
@humphd sorry I'm holding off on merging this because I'm testing the options part. It seems to not like `prettyPrint` as I'm unable to get the `logs` index to show.

What I wanted to ask was for example we have the following:

image

with this PR, we should have a new index called `logs`, if I have `LOG_LEVEL=info` set. Shouldn't the `docs.count` # be almost the same if not more than the `docs.count` # for posts? I'm asking this because the `docs.count` for logs is only 8 after running it for 2-3 hours. I was expecting it to be a much higher account with all the lines of `INFO` we're getting in the terminal

**Comment by humphd** [comment]
Yeah, that sounds odd to me (that it's so low).  What do you see in logs when you get those 8?

**Comment by c3ho** [comment]
🤷 I'm still trying to figure out how to use kibana so I can look inside those logs

**Comment by c3ho** [comment]
Nevermind, I got ~7k hits on logs just now.

**Comment by humphd** [comment]
It might be caching results and not flushing them to the db until some threshold is reached.

**Comment by c3ho** [comment]
I think that's the case with the `flush-bytes` setting.

**Comment by c3ho** [comment]
@humphd I put another ternary to check `LOG_ELASTIC` in `.env` if set we'll use `{ log: logLevel }` instead of options (so pino-elastic actually works), if we're not logging to elastic we'll use `options` and keep `prettyPrint`

**Review by humphd — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]
