### PR TITLE
Fixes #3611: Make RSS on Sign-up review page into snippets with hover display

### LINKED ISSUE #3611: Sign-up flow confirmation page has overflow
**What happened**:
There is overflow in the confirmation page for the sign-up flow
chrome_Xcc4I4UEmW

**What should have happened**:
Remove the overflow or handle it. 

**How to reproduce it (as precise as possible)**:
Complete sign up link  and get to the confirmation page.

### PR DESCRIPTION
**Pull request by cychu42**
## Issue This PR Addresses
 Fixes #3611 

## Type of Change
- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
eg

The RSS links on sign-up review page can be rather long and cause text overflow, so this PR turned them into snippets that will display the full text on hover. Overflow text is shorten with ellipses.

**Changes on `src/web/app/src/components/SignUp/Forms/Review.tsx`:**
- add `title={feedUrl}` to the RSS links in Blog RSS and Twitch/Youtube Channel RSS, to show text on hover
- added `RssContainer` and `RssContent` class for CSS
- assign `RssContainer` class to each RSS item, and wrap the actual RSS URL in  `RssContent` class `<span>`, to handle overflow
- fix typo from `Twich` to `Twitch` 
- add max width to `blogRSS` class's CSS to limit text length for overflow handling

## Steps to test the PR
Test this by going through the sign-up process to view the review page.
To see more comparable result with the issue filled, the following data can be used during testing: 
- GitHub user: AmasiaNalbandian
- Blog: https://dev.to/amasianalbandian
- Twitch Channels: http://www.twitch.tv/Opensrc http://www.twitch.tv/manekenpix

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/web/app/src/components/SignUp/Forms/Review.tsx [hunk 1]
```diff
@@ -125,16 +127,18 @@ const Review = connect<{ accountError: string | undefined }, SignUpForm>((props)
           </div>
           <div>
             <div className={classes.blogRss}>
-              <h3 className={classes.titleRss}>Blog RSS:</h3>
+              <h3 className={classes.titleRss}>Blog RSS Snippet:</h3>
```
Comment (humphd) [inline src/web/app/src/components/SignUp/Forms/Review.tsx:130]: I don't think you need this change, since it will show the full-text sometimes, and other times cut it off, but it will always be a URL.

File: src/web/app/src/components/SignUp/Forms/Review.tsx [hunk 2]
```diff
@@ -125,16 +127,18 @@ const Review = connect<{ accountError: string | undefined }, SignUpForm>((props)
...
               <div>
                 {blogs.map(({ feedUrl }) => (
-                  <h4 key={feedUrl}>{feedUrl}</h4>
+                  <h4 key={feedUrl} title={feedUrl}>
+                    {feedUrl}
+                  </h4>
                 ))}
               </div>
-              <h3 className={classes.titleRss}>Twich/Youtube Channel RSS:</h3>
+              <h3 className={classes.titleRss}>Twitch/Youtube Channel RSS Snippet:</h3>
```
Comment (humphd) [inline src/web/app/src/components/SignUp/Forms/Review.tsx:138]: Same thing here, remove "Snippet:"  Nice catch on `Twitch` spelling!

File: src/web/app/src/components/SignUp/Forms/Review.tsx [hunk 3]
```diff
@@ -125,16 +127,18 @@ const Review = connect<{ accountError: string | undefined }, SignUpForm>((props)
...
               <div>
                 {channels.map(({ type, feedUrl }) => (
-                  <h4 key={feedUrl}>
+                  <h4 key={feedUrl} title={feedUrl}>
```
Comment (humphd) [inline src/web/app/src/components/SignUp/Forms/Review.tsx:141]: Awesome to see you solve this with HTML.

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/web/app/src/components/SignUp/Forms/Review.tsx (hunk 1 above)
Comment (cychu42) [reply src/web/app/src/components/SignUp/Forms/Review.tsx:137]: Sure!

**Comment by cychu42** [comment]
I added the suggestions and redesigned my approach to make the ellipses happen. This PR is now ready for review.

Someone wrote an entire [guide](https://semicolon.dev/tutorial/css/text-overflow-ellipsis-doesnt-work) just for handling ellipses, which was really helpful. It seems this page is using grid, so I have to use a different way of making ellipses work.

**Comment by cychu42** [comment]
@humphd Since the draft, the main post's mentinon of changes and the picture are updated, if you want to see them.

File: src/web/app/src/components/SignUp/Forms/Review.tsx [hunk 4]
```diff
@@ -78,6 +78,7 @@ const useStyles = makeStyles((theme: Theme) =>
       textAlign: 'start',
     },
     blogRss: {
+      maxWidth: '300px',
```
Comment (humphd) [inline src/web/app/src/components/SignUp/Forms/Review.tsx:81]: Question: where did `300px` come from?

File: src/web/app/src/components/SignUp/Forms/Review.tsx [hunk 5]
```diff
@@ -91,6 +92,14 @@ const useStyles = makeStyles((theme: Theme) =>
       alignSelf: 'end',
       color: '#474747',
     },
+    RssContainer: {
```
Comment (humphd) [inline src/web/app/src/components/SignUp/Forms/Review.tsx:95]: `rssContainer`

File: src/web/app/src/components/SignUp/Forms/Review.tsx [hunk 6]
```diff
@@ -91,6 +92,14 @@ const useStyles = makeStyles((theme: Theme) =>
...
+      display: 'flex',
+    },
+    RssContent: {
```
Comment (humphd) [inline src/web/app/src/components/SignUp/Forms/Review.tsx:98]: `rssContent`

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/web/app/src/components/SignUp/Forms/Review.tsx (hunk 4 above)
Comment (cychu42) [reply src/web/app/src/components/SignUp/Forms/Review.tsx:81]: The UI shifts around if I use % instead, so I use px. I judged it by the way the UI looks and picked a number that seems like a good place to stop the overflow.

File: src/web/app/src/components/SignUp/Forms/Review.tsx (hunk 5 above)
Comment (cychu42) [reply src/web/app/src/components/SignUp/Forms/Review.tsx]: Ah, right. Fixed.

File: src/web/app/src/components/SignUp/Forms/Review.tsx (hunk 6 above)
Comment (cychu42) [reply src/web/app/src/components/SignUp/Forms/Review.tsx]: Fixed.

File: src/web/app/src/components/SignUp/Forms/Review.tsx (hunk 4 above)
Comment (humphd) [reply src/web/app/src/components/SignUp/Forms/Review.tsx:81]: I'd feel better if you looked at the surrounding code to figure out what the width used elsewhere in parent components is.  If you have to use a magic number like this, so be it.  But if you can avoid it, that would be better.

**Review by humphd — APPROVED** [review]
This looks great.  One question, but I don't think it needs to block this.

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM.

I agree with @humphd regarding the `maxWidth: 300px`. It would be a good idea to file an issue regarding it.

**Comment by humphd** [comment]
@cychu42 if you want to file a follow-up on the `300px` bit, that's fine.  But I'm merging this in the meantime.
