### PR TITLE
Fix: Dark mode not being applied fully when user logs in

### LINKED ISSUE #2100: Dark mode not being applied fully when user logs in
**What happened**:

When testing #2098, I noticed that the dark mode was not being fully applied in the timeline. This is how it looks like when you login and have your theme preference set to dark mode

Bad dark-mode image

This is not an issue with the light-mode theme, however. That's working as expected.

**What should have happened**:
The white portions of the timeline should be black as that's the color of choice when using dark mode.

**How to reproduce it (as precise as possible)**:
To reproduce this issue, simply login with your theme preference being set to dark mode prior to the login.

**Anything else we need to know?**:
This issue is dependent on #2098 landing, since this issue was found while testing the login portion of our front-end to make sure it works as expected.

**Environment**:

- OS: Microsoft Windows 10 Home
- Browser: Google Chrome

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes #2100 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This PR was a solution to solve the bug on my machine. 
It seems that for some reason MUI theme was causing the bug when used in the `Avatar` component. 

Tested on Chrome, Firefox and Safari. 

SAFARI(14.0.3):

FIREFOX(87.0 (64-bit)):

Chrome(Version 89.0.4389.114 (Official Build) (x86_64)):

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/web/src/components/TelescopeAvatar.tsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    )
+    .join('');
+  // splitName represents the current value, i represents its index, and arr represent the whole splitted name-word array
+  // if the index is 0, means it's the first word in the name
+  // if the index+1 equals to the array length, it means the current value is the last word in the name
+  // anything rather than first word or last word will not be included in initials
+  return initials;
+};
+
+const TelescopeAvatar = ({ name, img = '', size }: TelescopeAvatarProps) => {
```
Comment (humphd) [inline src/web/src/components/TelescopeAvatar.tsx:23]: Let's not use `img = ''`, and let it stay undefined if not present.

**Review by humphd — COMMENTED** [review]
Awesome, one issue.

**Comment by humphd** [comment]
Can you rebase to pick up the Vercel fix?

**Review by HyperTHD — DISMISSED** [review]

**Review by humphd — APPROVED** [review]

**Review by yuanLeeMidori — APPROVED** [review]

**Review by HyperTHD — APPROVED** [review]
