### PR TITLE
Fixing wrong build status url

### LINKED ISSUE #2747: Wrong url for fetching build status from the autodeployment server (Production)
**What happened**:
In **production**, the build log page fails to fetch build status information from the autodeployment server

image

**What should have happened**:
The build log page should display commit, status and build duration

**How to reproduce it (as precise as possible)**:
Check the build log page in telescope's dashboard (production)

**Anything else we need to know?**:
I did some testing and the issue seems to be [here](https://github.com/Seneca-CDOT/telescope/blob/855b39fa8a7d6e7020f2fe7f7a345607a0da9861/src/api/status/public/js/build-log/check-build-status.js#L5).
This works for `dev.api.telescope`, which results in `dev.telescope`, but in production it fails to turn `api.telescope` into `telescope` since the text to be replaced is `.api`.

We could probably use a regex to address this.

**Environment**:

- OS: Manjaro
- Browser: Firefox

### PR DESCRIPTION
**Pull request by tpmai22**
## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Fixed #2747 

You can review the `regex` [here](https://regex101.com/r/nIin6v/1)

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/api/status/public/js/build-log/check-build-status.js [hunk 1]
```diff
@@ -2,7 +2,7 @@
 // being loaded. On staging and production, remove the `api.` subdomain.
 // On localhost:1111, use localhost (drop the port).
 const autodeploymentUrl = (path) =>
-  `//${window.location.hostname.replace('.api', '')}/deploy${path}`;
+  `//${window.location.hostname.replace(/(?:api\.|\.api)/gm, '')}/deploy${path}`;
```
Comment (humphd) [inline src/api/status/public/js/build-log/check-build-status.js:5]: I think this can be simplified to `/(api\.|dev\.api\.)/` so it gets rid of the `api` or `dev.api` bits

**Review by humphd — CHANGES_REQUESTED** [review]

File: src/api/status/public/js/build-log/check-build-status.js (hunk 1 above)
Comment (humphd) [reply src/api/status/public/js/build-log/check-build-status.js:5]: Yes, you're right, so it could be simplified to `/api\./`, right?

Comment (tpmai22) [reply src/api/status/public/js/build-log/check-build-status.js:5]: @humphd Follow what I read [here](https://www.ocpsoft.org/tutorials/regular-expressions/or-in-regex/) 

> If you don’t want your grouping and alternation to interfere with other numbered groups in your expression, each “or” group must be prefixed with `?:`

I guess I try to avoid any cache if not needed, or do you think `/api\./` should be enough without any performance issue ?

Comment (humphd) [reply src/api/status/public/js/build-log/check-build-status.js:5]: There's zero performance issue for a regex on a string of this size.

File: src/api/status/public/js/build-log/check-build-status.js [hunk 2]
```diff
@@ -2,7 +2,7 @@
 // being loaded. On staging and production, remove the `api.` subdomain.
 // On localhost:1111, use localhost (drop the port).
 const autodeploymentUrl = (path) =>
-  `//${window.location.hostname.replace('.api', '')}/deploy${path}`;
+  `//${window.location.hostname.replace(/(api\.|\.api)/gm, '')}/deploy${path}`;
```
Comment (humphd) [inline src/api/status/public/js/build-log/check-build-status.js:5]: You don't need `/gm` flags.

**Review by humphd — CHANGES_REQUESTED** [review]

**Comment by tpmai22** [comment]
I think we are good to go now

**Review by humphd — APPROVED** [review]

**Review by cindyledev — APPROVED** [review]
