### PR TITLE
Fix #25: Implement basic email sender

### LINKED ISSUE #25: Implement ability to email admins/users
This issue is a part of the [MVP Features](https://github.com/Seneca-CDOT/telescope/blob/master/docs/overview.md#mvp-features).

It should send an email to an admin or the user if:

- A post is deemed inappropriate
- Any major errors are logged (ex. issues downloading feeds)
- If it crashed

If there any other times an email should be sent out please suggest them as well.

### PR DESCRIPTION
**Pull request by RyanWils**
Contributes to issue #25 

I created a basic email sender using Nodemailer. 
To use the function, private information(email/pass,recipients) must be filled once the .env variables are set up. 

refer to issue #82 for the tests.

I have also left a comment at the top of the file on how to use this file. 
1. import the file (const sendEmail = require('./email-sender);) 
2. send email (sendEmail.sendMessage("Put your error message in here");)

### CODE REVIEW

**Comment by humphd** [comment]
@RyanWils you can't share username/password pairs on GitHub like this.  Please get rid of this account.

File: src/email-sender.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+    //Recipients list of users to send the email too
+    var receipiants = 'rwilson31@myseneca.ca,david.humphrey@senecacollege.ca';
+
+    //Credientials to send an email from 
+    var transporter = nodemailer.createTransport({
+        service: 'gmail',
+        auth: {
+            user: 'seneca.telescope@gmail.com',
+            pass: 'Password12345%^'
```
Comment (humphd) [inline src/email-sender.js]: This is a no-go.  Username/Password pairs need to get read in via environment variables on `process.env`

Comment (RyanWils) [reply src/email-sender.js]: Okay thank you, Sorry. It was a test email, I have deleted the account. 
Will change the code ASAP.

**Comment by RyanWils** [comment]
I apologies for putting private information on the previous commit. 
I have removed the personal information in the newest commit and also deleted that test email I was using.  
It seems like there is an issue open for the .env variables - issue #60
I have left the variables blank for when this issue is completed.

**Comment by humphd** [comment]
I wonder if we should use something like https://sendgrid.com/ for the mail transport layer.  Creating an account in GMail or the like isn't sustainable when it's shared among so many users.  There might be other services too, but this is one that came to mind, since we could use it long term for free.

**Comment by RyanWils** [comment]
Thank you for the suggestion, it seems like a good choice (40,000 emails for the first 30 days, then 100/day forever. should be plenty). Ya you make a good point, I think its best to switch from Nodemailer

**Comment by humphd** [comment]
@RyanWils I'm not sure if it's what we want or not, but something for you to look at.  I think you could use it *with* nodemailer, or use their node.js API.  Needs research.

**Comment by humphd** [comment]
https://www.sendinblue.com/ is another one, there are a bunch.

**Comment by humphd** [comment]
Using one of these services, for devs who want to hack on the email portion of the code, they could sign up for their own API key, put it in their `.env` and then they could work on that part of the code.  In production, we'd use a different one.

**Comment by RyanWils** [comment]
Ya that would be for the best. For whichever service I pick, I will make sure to document the set up steps.

**Comment by RyanWils** [comment]
Do we want to send an actual email to the users?
I have tested sendgrid and they dont actually send an email, but store it in their activity feed.
image
What are we looking for?

**Comment by RyanWils** [comment]
I messed up on the titles of my commits for the Travis CI fixes as it references other topics. 
I have tried to reword my comments with git rebase -i master, but I cannot as the head is detached.
Anyone have any experience with this?

**Comment by c3ho** [comment]
@RyanWils I'm not sure if [this ](https://stackoverflow.com/questions/10228760/fix-a-git-detached-head/17045215)may help, but it sounds like you went back to some previous commits and changed from there.

**Comment by RyanWils** [comment]
Hi Calvin thanks for the solution, but sadly that solution did not work as my master is up to date. I created this pull request 6 days ago, so a lot of stuff got merged and even though I pulled into my master and rebased my branch into master it still says its detached. 

Screenshots of the issue 
image

says this for all the commits
image

File: src/email-sender.js [hunk 2]
```diff
@@ -9,9 +9,9 @@ const nodemailer = require('nodemailer');
 exports.sendMessage = async function (errorMessage) {
   // Recipients list of users to send the email too
   // receipiants is commas separated (emailName@hotmail.com,emailName2@hotmail.com)
-  var receipiants = '';
+  const receipiants = '';
```
Comment (neilong31) [inline src/email-sender.js]: Hey @RyanWils ! Something that I've noticed is that we have a recipients const, but we never have a way to update who the recipients are in the scope of this function. Maybe we can add a way to pass sendMessage the recipients in a array of strings?

File: src/email-sender.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+  const mailOptions = {
+    from: '', // Email Name
+    to: receipiants,
+    subject: 'Seneca Telescope had an error', // Subject Line
+    html: `<p>An Error has occurred <br/>Error Message: ${errorMessage} </p>`, // Message Body
+  };
+
+  // Send the email with the email content
+  transporter.sendMail(mailOptions, (err, info) => {
+    if (err) {
```
Comment (neilong31) [inline src/email-sender.js]: Hey @RyanWils ! Maybe we could return and err if it transporter.sendMail() doesn't work and a true or something else if it does. This would make it easier to test for future development. What do you think?

File: src/email-sender.js (hunk 2 above)
Comment (RyanWils) [reply src/email-sender.js]: Hi Neil I was thinking about the same changes to make to the send message function, but i think that should be implemented down the road because it would be a hassle to create an array of string every time you want to call this function. We can implement an optional parameters down the road once we start using it.

File: src/email-sender.js (hunk 3 above)
Comment (RyanWils) [reply src/email-sender.js]: Ya as you highlighted in your suggestion, the transporter sends the email and will print an error if it unsuccessful/print the information if it does not have an error. From my knowledge this is not reliable because just like the other frameworks to send emails, Nodemailer just send a message to the outlook server and if its received successfully by the outlook server it returns true. Even if the email does not send to the user, as long as it is received by the outlook server it will return true. This is where you tests come in, maybe we can find something that returns false if it cannot find an email.

File: src/email-sender.js [hunk 4]
```diff
@@ -0,0 +1,39 @@
+const nodemailer = require('nodemailer');
+
+/*
+*                             HOW TO USE                                 *
+* Import this file - const sendEmail = require('./email-sender);         *
+* send email - sendEmail.sendMessage("Put your error message in here");  *
+*/
+
+exports.sendMessage = async function (errorMessage) {
```
Comment (humphd) [inline src/email-sender.js]: We need to add a way to specify a few things, at the very least:

1. To
1. Subject
1. Body

I would put these in as params to the function.

File: src/email-sender.js [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+  // Recipients list of users to send the email too
+  // receipiants is commas separated (emailName@hotmail.com,emailName2@hotmail.com)
+  const receipiants = '';
+
+  // Credientials to send an email from
+  const transporter = nodemailer.createTransport({
+    service: 'gmail',
+    auth: {
+      user: '', // Email Name (.env variables must be used refer to issue#60)
+      pass: '', // Email Pass (.env variables must be used refer to issue#60)
```
Comment (humphd) [inline src/email-sender.js]: Let's do `SMTP_SERVER`, `SMTP_USERNAME`, `SMTP_PASSWORD` as environment variables in `env.sample`, and you can read them from `process.env`

File: src/email-sender.js [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+    },
+  });
+
+  // Email Content
+  const mailOptions = {
```
Comment (humphd) [inline src/email-sender.js]: Let's allow users to pass this in to your function directly, and we can validate that the required bits are here or error.

File: src/email-sender.js (hunk 4 above)
Comment (humphd) [reply src/email-sender.js]: Another thing you need to do, is properly wrap the callback style of nodemailer into a Promise:

```js
// This needs to return a Promise
async function doSomething() {
  return new Promise((resolve, reject) => {
    ...
    sendMail(options, function(err, info) {
        if(err) reject(err);
        else resolve(info);
    });
  });
}
```

or you can do it using [util.promisify()](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original)

File: env.example [hunk 7]
```diff
@@ -6,3 +6,12 @@ PORT=8080
...
 REDIS_URL=redis://127.0.0.1:6379
+
+# NODEMAILER_USERNAME is sender's username credential	
+NODEMAILER_USERNAME=	
+
+# NODEMAILER_PASSWORD is sender's password credential	
+NODEMAILER_PASSWORD=
+
+# NODEMAILER_SERVER is sender's server that they are using (Example: Gmail)
+NODEMAILER_SERVER=
```
Comment (humphd) [inline env.example]: This is wrong for a server, see https://nodemailer.com/smtp/

File: src/email-sender.js [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+      subject: subjectMessage, // Subject Line
+      html: message, // Message Body
+    };
+
+    // Send the email with the email content
+    transporter.sendMail(mailOptions, (err, info) => {
+      if (err) {
+        reject(err); // Send promise.reject if an error occurs
+      } else {
+        resolve(info); // Send promise.resolve if an error occurs
```
Comment (neilong31) [inline src/email-sender.js]: One quick thing, could we resolve with info.accepted? That way with our test we can just test if it resolves with the correct recipients?

Comment (RyanWils) [reply src/email-sender.js]: ya for sure, let me include it

Comment (RyanWils) [reply src/email-sender.js]: would you like me to use info.rejected as well for the reject or is the error enough?

Comment (neilong31) [reply src/email-sender.js]: Ah yes, could you please add that as well? After that I think it should be all good!

Comment (neilong31) [reply src/email-sender.js]: No, I think it's good actually! It should return the error.

Comment (RyanWils) [reply src/email-sender.js]: okay anything to change, if there isn't we should be good to merge. 
If there isn't anything please approve of these changes, thanks.
