### PR TITLE
[next] Fixes #1546: Ported SearchResults to NextJS and fixed styling on search error

### LINKED ISSUE #1458: [next] Update 500 error UI styling for failed search
When our Elasticsearch server fails, and we send the browser a 500, we show an error message:

Screen Shot 2020-11-25 at 4 22 18 PM

Let's improve the look of this to be more consistent with the app.  There is some similar discussion for "no results" happening in #1413, and maybe we can do a similar visual in both cases.

### LINKED ISSUE #1546: [next] Port SearchResults to NextJS
https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/gatsby/src/components/SearchPage/SearchResults.jsx
**What would you like to be added**:
Port SearchResults component to NextJS using TS
**Why would you like this to be added**:
Porting reason

### PR DESCRIPTION
**Pull request by rjayroso**
## Issue This PR Addresses
Fixes #1546 (Port SearchResults to NextJS)
Fixes #1458 (Update error styling for failed search)
Closes #1512 (The original 1458 issue was worked on by @sonechca and his resulting PR's work was essentially merged into this one and updated)

## Type of Change
- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI
- [x] **Next.JS Port** 

## Description
This PR ports SearchResults component from Gatsby to NextJS. This PR also includes an update on the search error styling.

Notable changes are the removal of the `loading` variable from `const { data, size, loading, setSize, error } = useSWRInfinite(//...)`  
`loading` is now declared as `const loading = !data && !error;`

`className={classes.root}` attribute was removed from `<Box className={classes.root} boxShadow={2} marginTop={10}>` since `classes.root` doesn't exist (*Typescript complained whereas in the original JSX file this was not an issue*). 

CSS styling additions of `errorBackground`, `errorTitle`, and `errorMessage` were added to update the error styling.

#### How to Test
Import the SearchResults component into a NextJS page (I used the index.tsx to test):
`import SearchResults from '../components/SearchResults'`  

Now create a SearchResults component and pass in some data:
e.g. it might look like this ` <SearchResults text={"Search for me"} filter={"I am a filter"}/>`

Save the code and then refresh the page, you should see something similar to this:
image

To check the responsiveness, inspect the page (right-click the page -> inspect) and toggle device toolbar. For resulting example, see below:

Styling was taken from PR #1512 and updated to be responsive, see below:
| Before | After |
| :---: | :---: |
| image | image

## Checklist
- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/next/src/components/SearchResults.tsx [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+  if (error) {
+    return (
+      <Container className={classes.searchResults}>
+        <Box boxShadow={2} marginTop={10}>
+          <div className={classes.errorBackground}>
+            <div>
+              <p className={classes.errorTitle}>Search Error</p>
+              <p className={classes.errorMessage}>
+                There was an server error while processing your query
```
Comment (HyperTHD) [inline src/frontend/next/src/components/SearchResults.tsx:74]: Small typo, should be "a server" instead of "an server"

**Review by HyperTHD — APPROVED** [review]
Other than the typo, looks good otherwise. I'm a little uneasy with the way it looks on mobile, but that's probably because the banner component hasn't been added yet.

**Review by chrispinkney — COMMENTED** [review]
Getting:
```Unhandled Runtime Error

TypeError: page.map is not a function```
from `Timeline.tsx` after checking out this PR. Any ideas? Master runs just fine for me until I test this in `pages/index.tsx`

![firefox_2021-01-29_18-54-50](https://user-images.githubusercontent.com/7242003/106339060-80f8b780-6263-11eb-8a9c-ebb3c832937b.png)

**Comment by rjayroso** [comment]
@chrispinkney wow I've never seen it say anything about that before, I don't think I touched anything in Timeline.tsx but if I had to guess it has to do something with maybe how I set up my environment(?). I set it up so that my backend comes from the dev server  instead of running docker locally.

File: src/frontend/next/src/components/SearchResults.tsx (hunk 1 above)
Comment (rjayroso) [reply src/frontend/next/src/components/SearchResults.tsx:74]: Oh I think that is left over from sonecha's styling fix. I'll push a change to fix that now, thanks!

**Comment by rjayroso** [comment]
Can I see how you imported the component and implemented it in your `pages/index.tsx`?

**Comment by PedroFonsecaDEV** [comment]
> Getting:
> 
> ```
> Unhandled Runtime Error
> 
> TypeError: page.map is not a function
> ```
> 
> from `Timeline.tsx` after checking out this PR. Any ideas? Master runs just fine for me until I test this in `pages/index.tsx`
> 
> firefox_2021-01-29_18-54-50

I don't think this bug is related to this PR.

File: src/frontend/next/src/components/SearchResults.tsx [hunk 2]
```diff
@@ -0,0 +1,104 @@
+import { makeStyles } from '@material-ui/core/styles';
```
Comment (PedroFonsecaDEV) [inline src/frontend/next/src/components/SearchResults.tsx:1]: `import { createStyles, makeStyles, Theme } from '@material-ui/core/styles';`

File: src/frontend/next/src/components/SearchResults.tsx [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+import { useSWRInfinite } from 'swr';
+import { Container, Box } from '@material-ui/core';
+
+import useSiteMetadata from '../hooks/use-site-metadata';
+import Timeline from './Posts/Timeline';
+import Spinner from './Spinner';
+
+const useStyles = makeStyles(() => ({
```
Comment (PedroFonsecaDEV) [inline src/frontend/next/src/components/SearchResults.tsx:9]:
``` js
const useStyles = makeStyles((theme: Theme) => 
createStyles({ spinner: {
    display: 'flex',
    justifyContent: 'center',
  },
  ...
```

**Review by PedroFonsecaDEV — CHANGES_REQUESTED** [review]

File: src/frontend/next/src/components/SearchResults.tsx (hunk 3 above)
Comment (HyperTHD) [reply src/frontend/next/src/components/SearchResults.tsx:9]: The theme object is not used here, so it's not needed. It's mostly used to access the palette object, which again, SearchResults is not using here

**Comment by HyperTHD** [comment]
> > Getting:
> > ```
> > Unhandled Runtime Error
> > 
> > TypeError: page.map is not a function
> > ```
> > 
> > 
> > from `Timeline.tsx` after checking out this PR. Any ideas? Master runs just fine for me until I test this in `pages/index.tsx`
> > firefox_2021-01-29_18-54-50
> 
> Let's investigate this bug in a different thread because I don't think it is related to this PR.

The SearchPage won't be able to land with this issue still intact, we must solve it here

**Comment by humphd** [comment]
How can I reproduce this `pages.map` error?  I'd like to look into it.

File: src/frontend/next/src/components/SearchResults.tsx [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+          <Spinner />
+        </h1>
+      </Container>
+    );
+  }
+
+  return (
+    <Container className={classes.searchResults}>
+      {data && data.length ? (
+        <Timeline pages={data} nextPage={() => setSize(size + 1)} />
```
Comment (humphd) [inline src/frontend/next/src/components/SearchResults.tsx:96]: If `data` is an array of Posts, you need to wrap it in another array so it's `[ [post, post, ...] ]` (i.e., an array of pages of posts, or pages of page of post).  Fix would be: `pages={[data]}`.  Test that and see.

**Review by humphd — CHANGES_REQUESTED** [review]

**Comment by manekenpix** [comment]
I think this is a filter issue. Currently, our filter only accepts `posts` or `author`. Any other value would cause the `page.map` error. I'm testing using `author` or `posts` as filters and it works wonderfully.

**Comment by manekenpix** [comment]
Peek 2021-01-31 21-42

**Comment by humphd** [comment]
Interesting.  In TS we can capture that with `type Filter = 'post' | 'author'`

**Comment by rjayroso** [comment]
> Interesting. In TS we can capture that with `type Filter = 'post' | 'author'`

Would this statement be in the `SearchResults.tsx` component or in the Search page (before we pass the filter prop)?

**Comment by humphd** [comment]
@rjayroso anything that relies on that typing would need it, just like you might use `string` in multiple places for a String type.

**Comment by rjayroso** [comment]
I added `type Filter = 'post' | 'author';`, and have gotten the same results as @manekenpix. As long as filter is either post or author, it no longer gives us that `page.map` error.
I tested it further with the change you suggested but when I wrapped `data` in another array  (`pages={data}` to `pages={[data]}`), it gave me this:
image

File: src/frontend/next/src/components/SearchResults.tsx [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+    margin: '2rem',
+    color: '#96C1E7',
+  },
+}));
+
+type Filter = 'post' | 'author';
+
+type SearchResultProps = {
+  text: string;
+  filter: Filter;
```
Comment (humphd) [inline src/frontend/next/src/components/SearchResults.tsx:47]: Get rid of 43 and do this inline, since we don't do anything else with `Filter`:

`filter: 'post' | 'author';`

Comment (humphd) [reply src/frontend/next/src/components/SearchResults.tsx:47]: One thing to consider: we might want to define `Filter` like you did on 43 in one file and export it, so we can use it again in another.  I'm not sure who the owner of the type should be, maybe the root search page?  Regardless, that can happen in an other PR.  cc @c3ho, who I think will have to deal with this.

**Review by humphd — CHANGES_REQUESTED** [review]

**Comment by humphd** [comment]
Let's rebase this too

**Review by humphd — APPROVED** [review]

**Review by PedroFonsecaDEV — APPROVED** [review]
