### PR TITLE
[next] Fixes issue#1481: re-implements the LogoIcon component

### LINKED ISSUE #1481: [next] Add LogoIcon
**What would you like to be added**:
LogoIcon!

**When do we want it?**:
Now!

**Why would you like this to be added**:
See #1316

### PR DESCRIPTION
**Pull request by chrispinkney**
Fixes #1481:
* Added LogoIcon component and the `.svg` Telescope logo.

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Re-implements the `LogoIcon` component in next.js using a webp version of the logo (because, why not? _but seriously I can change it back if required, I was just curious about the webp format_).

Simply import and call LogoIcon while specifying a size and we're off to the races:

```TS
import LogoIcon from './LogoIcon';
<LogoIcon height={320} width={320} />
```

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/next/src/pages/LogoIcon.tsx [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+
+// Explicitly state that LogoIcon can only accept numbers as a type when creating a Logo
+const LogoIcon = ({ height, width }: { height: number; width: number }) => {
+  return (
+    <>
+      <Image src={Logo} alt="Telescope Logo" height={height} width={width} />
+    </>
+  );
+};
+
```
Comment (tonyvugithub) [inline src/frontend/next/src/pages/LogoIcon.tsx:13]: Maybe create an interface for props type and call it LogoIconProps
```
import {FC} from 'react';
const interface LogoIconProps {
    height: number,
    width: number,
}
const LogoIcon: FC<LogoIconProps> = ({height, width}) => {
    .....
}
```

Comment (tonyvugithub) [reply src/frontend/next/src/pages/LogoIcon.tsx:13]: FC stands for functional component that would take in props in the form of LogoIconProps

**Review by tonyvugithub — CHANGES_REQUESTED** [review]

File: src/frontend/next/src/pages/LogoIcon.tsx (hunk 1 above)
Comment (chrispinkney) [reply src/frontend/next/src/pages/LogoIcon.tsx:19]: Kk on it!

**Review by humphd — CHANGES_REQUESTED** [review]
Webp is not supported in all browsers.  If you want to do this, you need to use `<picture>` and provide different sources, with a fallback to JPG.

I'm not sure that webp gains us much here with such a small image.

Also, if we put the files in `public/` don't we get to use them for free without needing `next-images` and config changes?

**Comment by chrispinkney** [comment]
I'm getting some eslint errors when trying to import my component and I'm not sure why- although the component does import and works as expected. :shrug:

File: src/frontend/next/src/pages/LogoIcon.tsx [hunk 2]
```diff
@@ -0,0 +1,18 @@
+import { FC } from 'react';
+import Image from 'next/image';
```
Comment (humphd) [inline src/frontend/next/src/pages/LogoIcon.tsx:2]:
```
7:25:05 PM: Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
Possible solutions:
7:25:05 PM:   - Use `next start`, which starts the Image Optimization API.
7:25:05 PM:   - Use Vercel to deploy, which supports Image Optimization.
7:25:05 PM:   - Configure a third-party loader in `next.config.js`.
7:25:05 PM: Read more: https://err.sh/next.js/export-image-api
7:25:05 PM:     at exportApp (/opt/build/repo/src/frontend/next/node_modules/next/dist/export/index.js:14:712)
```

We can't use `Image` unfortunately, it only works with server-side optimization (ie., you have to run a server to create dynamic images on demand).  For pure static/exported projects, it's not possible.

File: src/frontend/next/src/pages/LogoIcon.tsx [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+
+// This interface specifies that the props passed in can only be of type number
+interface LogoIconProps {
```
Comment (humphd) [inline src/frontend/next/src/pages/LogoIcon.tsx:5]: This should be `type` vs. `interface`

**Review by humphd — CHANGES_REQUESTED** [review]
Why have you removed next.config.js?

**Comment by chrispinkney** [comment]
> 
> 
> Why have you removed next.config.js?

@humphd I was using the `next-images` library and because of that I had to create the file, but since I just removed the library I deleted the file as well as it added nothing but configuration for the library.

File: src/frontend/next/src/pages/LogoIcon.tsx (hunk 3 above)
Comment (chrispinkney) [reply src/frontend/next/src/pages/LogoIcon.tsx]: Done!

File: src/frontend/next/src/pages/LogoIcon.tsx (hunk 2 above)
Comment (chrispinkney) [reply src/frontend/next/src/pages/LogoIcon.tsx]: That's too bad. Ah well, I removed it.

File: src/frontend/next/src/pages/LogoIcon.tsx [hunk 4]
```diff
@@ -0,0 +1,17 @@
+import { FC } from 'react';
+
```
Comment (tonyvugithub) [inline src/frontend/next/src/pages/LogoIcon.tsx:2]: @chrispinkney : The path should be `/src/components/LogoIcon/LogoIcon.tsx`. Also can you squash into 1 commit instead of 2?

**Review by tonyvugithub — CHANGES_REQUESTED** [review]

File: src/frontend/next/src/pages/LogoIcon.tsx (hunk 4 above)
Comment (chrispinkney) [reply src/frontend/next/src/pages/LogoIcon.tsx]: Done like dinner.

**Review by humphd — APPROVED** [review]
The FC and file layout can be fixed later if you want, this is good otherwise.

**Review by tonyvugithub — APPROVED** [review]
