### PR TITLE
Fix #1630 - triggering search via URL

### LINKED ISSUE #1630: Triggering search through URL doesn't work.
**What happened**:
#1583 will land soon, triggering search through normal use works, but triggering search through URL doesn't work.

**What should have happened**:
Triggering search through search function AND url should work like it does in our current front-end

**How to reproduce it (as precise as possible)**:
Does work:
Go to /search and choose a filter, type in text to search. Results will display

Does not work:
Type /search?filter=post&text=Telescope. No results will display.
**Anything else we need to know?**:

**Environment**:

- OS: Mac
- Browser: Chrome

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes #1630

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/next/src/components/SearchPage.tsx [hunk 1]
```diff
@@ -38,11 +36,13 @@ const SearchPage = () => {
...
     event.preventDefault();
-    setTextParam(text);
-    setFilterParam(filter);
     router.push(`/search?text=${text}&filter=${filter}`);
   }
 
+  useEffect(() => {
+    setText(textParam);
+    setFilter(filterParam);
+  }, [textParam, filterParam]);
```
Comment (humphd) [inline src/frontend/next/src/components/SearchPage.tsx:45]: Add a black line below this, before the `return (`

**Review by humphd — CHANGES_REQUESTED** [review]
One small fix, and this is good to go!

File: src/frontend/next/src/components/SearchPage.tsx (hunk 1 above)
Comment (DukeManh) [reply src/frontend/next/src/components/SearchPage.tsx:45]: It has been updated.

**Review by humphd — APPROVED** [review]

**Review by PedroFonsecaDEV — APPROVED** [review]
