### PR TITLE
Mobile can access hamburger menu

### LINKED ISSUE #860: Hamburger menu button cannot be accessed in small devices
**What happened**:
Hamburger menu button cannot be accessed in small devices such as the Samsung S5. The navbar starts looking really cluttered for screens smaller than 430px
Annotation 2020-03-22 220613

**What should have happened**:
Header should only show Telescope title and hamburger menu button to toggle to see side drawer on small screen devices
- Search
- About

**How to reproduce it (as precise as possible)**:
View https://dev.telescope.cdot.systems/ on small screen device

**Anything else we need to know?**:
Bonus: Add icons to Search and About in the side drawer

**Environment**:
- OS: Windows -> Android
- Browser: Chrome using DevTool to inspect device toolbar

### PR DESCRIPTION
**Pull request by agarcia-caicedo**
## Issue This PR Addresses
fixes #860 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Mobile and Desktop now have different headers to best use their space

Desktop Header:
image

Mobile Header:
image

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

File: src/frontend/src/components/MobileHeader/MobileHeader.jsx [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+
+  const sideList = (side) => (
+    <div
+      className={classes.list}
+      role="presentation"
+      onClick={toggleDrawer(side, false)}
+      onKeyDown={toggleDrawer(side, false)}
+    >
+      <List>
+        <ListItem className={classes.item}>
```
Comment (cindyledev) [inline src/frontend/src/components/MobileHeader/MobileHeader.jsx:88]: Small nit: 
Using HOME as an example here, this PR doesn't make the entire ListItem clickable, I would have to click on the HOME text to get to where I wanna go. If I click outside of the HOME but still inside of the ListItem, it closes the drawer but I'm still on the same page. This gives me the impression that the button doesn't work.

I suggest `<ListItem button component={Link} className={classes.item}>` for all ListItems, this will allow the entire ListItem to be clickable for better user experience :D

File: src/frontend/src/components/Header/Header.jsx [hunk 2]
```diff
@@ -86,9 +86,19 @@ const Header = () => {
     >
       <List>
         <ListItem className={classes.item}>
```
Comment (cindyledev) [inline src/frontend/src/components/Header/Header.jsx:88]: Same suggestion here

File: src/frontend/src/components/Header/Header.jsx [hunk 3]
```diff
@@ -86,9 +86,19 @@ const Header = () => {
...
-          <Link to="/search" className={classes.links}>
-            Search
-          </Link>
+          <Button color="inherit" size="medium" className={classes.button}>
+            <Link to="/search" className={classes.links}>
```
Comment (humphd) [inline src/frontend/src/components/Header/Header.jsx:90]: If we have Search in the menu, do we also need it in the header bar for mobile?  I'd suggest it only needs to be in one, not both places.

**Comment by humphd** [comment]
If you want to refactor this so the login stuff lives in the header vs. its own components, that's fine.

File: src/frontend/src/pages/PageBase.js [hunk 4]
```diff
@@ -25,11 +27,17 @@ const styles = {
...
 
 function PageBase({ children, title }) {
+  const theme = useTheme();
+  const matches = useMediaQuery(theme.breakpoints.down('sm'));
   return (
     <>
       <CssBaseline />
       <SEO title={title} />
-      <Header />
+      {matches === true ? (
```
Comment (humphd) [inline src/frontend/src/pages/PageBase.js:36]: This is leaking too much abstraction about the Header component.  Let's move all the stuff you're doing here into the Header component, and in the render function, do what you're doing here and choose which Header you actually want to display.  The `PageBase` can just use `<Header />` and you can hide all this complexity where it's needed, in the Header code itself.
